/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import {
  joinPathFragments,
  type MigrationReturnObject,
  type Tree,
} from '@nx/devkit';
import { applyGritQL, matchGritQL } from '../../../utils/ast.js';
import { formatFilesInSubtree } from '../../../utils/format.js';
import {
  PACKAGES_DIR,
  SHARED_TERRAFORM_DIR,
} from '../../../utils/shared-constructs-constants.js';

/**
 * Hand the Aurora admin credentials to RDS, which generates and rotates them in
 * Secrets Manager and never reveals the password to Terraform.
 *
 * The module previously minted the master password with `random_password` and
 * wrote it into an `aws_secretsmanager_secret_version`, so both the generated
 * value and the full secret string were stored in plaintext in Terraform state.
 * `manage_master_user_password` removes both, matching the CDK construct's
 * `Credentials.fromGeneratedSecret`.
 *
 * RDS rotates a managed secret natively, so the CloudFormation rotation stack
 * and the security groups that reached its hosted Lambda go away with it.
 *
 * A managed secret holds only `username` and `password`, so the handlers that
 * read it take the host, port and database name from their environment.
 *
 * Switching an existing cluster is an in-place `ModifyDBCluster` — RDS
 * generates a new password and stores it in a new managed secret, leaving the
 * data, endpoints and cluster identifier untouched. Diverged files are left
 * alone and reported via `nextSteps`.
 */

const TERRAFORM_AURORA_FILE = `${PACKAGES_DIR}/${SHARED_TERRAFORM_DIR}/src/core/rdb/aurora/aurora.tf`;
const TERRAFORM_DBS_DIR = `${PACKAGES_DIR}/${SHARED_TERRAFORM_DIR}/src/app/dbs`;

const hcl = (pattern: string) => `language hcl\n${pattern}`;

const auroraDivergedMessage = () =>
  `${TERRAFORM_AURORA_FILE}: has diverged from the generated shape - left untouched. The admin password is generated by \`random_password\` and stored in Terraform state in plaintext. To close that, set \`manage_master_user_password = true\` and \`master_user_secret_kms_key_id\` on aws_rds_cluster.database, drop the random_password / aws_secretsmanager_secret / aws_secretsmanager_secret_version resources and the aws_cloudformation_stack rotation stack, and read the secret ARN from \`aws_rds_cluster.database.master_user_secret[0].secret_arn\`.`;

const appModuleDivergedMessage = (filePath: string) =>
  `${filePath}: has diverged from the generated shape - left untouched. An RDS-managed admin secret holds only username and password, so add DATABASE_HOST, DATABASE_PORT and DATABASE_NAME (from the aurora module's writer_endpoint, cluster_port and database_name outputs) to the create-db-user and migration Lambda environments, and stop passing enable_credential_rotation to the aurora module.`;

/** The resources whose sole purpose was minting and storing the password. */
const REMOVED_CREDENTIAL_RESOURCES = [
  '`resource "random_password" "master_password" { $_ }`',
  '`resource "aws_secretsmanager_secret" "credentials" { $_ }`',
  '`resource "aws_secretsmanager_secret_version" "credentials" { $_ }`',
];

/** The rotation stack RDS-managed rotation replaces, and its plumbing. */
const REMOVED_ROTATION_RESOURCES = [
  '`resource "aws_cloudformation_stack" "credentials_rotation" { $_ }`',
  '`resource "aws_security_group" "rotation" { $_ }`',
  '`resource "aws_vpc_security_group_egress_rule" "rotation_to_database" { $_ }`',
  '`resource "aws_vpc_security_group_ingress_rule" "rotation_to_database" { $_ }`',
];

const migrateCoreModule = async (
  tree: Tree,
  nextSteps: string[],
): Promise<void> => {
  // Already migrated.
  if (
    await matchGritQL(
      tree,
      TERRAFORM_AURORA_FILE,
      hcl('`manage_master_user_password = true`'),
    )
  ) {
    return;
  }

  // Only rewrite the shape the generator produced: the cluster taking its
  // password from random_password, and the secret version holding it.
  const anchors = [
    hcl(
      '`resource "aws_rds_cluster" "database" { $props }` where { $props <: contains `master_password = random_password.master_password.result` }',
    ),
    hcl(REMOVED_CREDENTIAL_RESOURCES[0]),
    hcl(REMOVED_CREDENTIAL_RESOURCES[2]),
  ];
  const allPresent = (
    await Promise.all(
      anchors.map((pattern) =>
        matchGritQL(tree, TERRAFORM_AURORA_FILE, pattern),
      ),
    )
  ).every(Boolean);

  if (!allPresent) {
    nextSteps.push(auroraDivergedMessage());
    return;
  }

  // RDS generates and holds the password; Terraform only ever sees the ARN.
  await applyGritQL(
    tree,
    TERRAFORM_AURORA_FILE,
    hcl(
      '`master_password = random_password.master_password.result` => `manage_master_user_password         = true\n  master_user_secret_kms_key_id       = aws_kms_key.database.arn`',
    ),
  );

  for (const resource of [
    ...REMOVED_CREDENTIAL_RESOURCES,
    ...REMOVED_ROTATION_RESOURCES,
  ]) {
    await applyGritQL(tree, TERRAFORM_AURORA_FILE, hcl(`${resource} => \`\``));
  }

  // Outputs that read the deleted secret resources.
  await applyGritQL(
    tree,
    TERRAFORM_AURORA_FILE,
    hcl(
      '`value = aws_secretsmanager_secret.credentials.arn` => `value       = aws_rds_cluster.database.master_user_secret[0].secret_arn`',
    ),
  );
  await applyGritQL(
    tree,
    TERRAFORM_AURORA_FILE,
    hcl(
      '`value = jsondecode(aws_secretsmanager_secret_version.credentials.secret_string).username` => `value       = aws_rds_cluster.database.master_username`',
    ),
  );
  await applyGritQL(
    tree,
    TERRAFORM_AURORA_FILE,
    hcl(
      '`description = "Admin username stored in the generated secret."` => `description = "Admin username stored in the RDS-managed credentials secret."`',
    ),
  );
  await applyGritQL(
    tree,
    TERRAFORM_AURORA_FILE,
    hcl(
      '`description = "ARN of the generated admin credentials secret."` => `description = "ARN of the RDS-managed admin credentials secret. Its value is a JSON object with username and password only — connection details come from this module\'s other outputs."`',
    ),
  );

  // Secrets Manager encrypts the managed secret with the module's own CMK.
  await applyGritQL(
    tree,
    TERRAFORM_AURORA_FILE,
    hcl(`\`Sid = "AllowRDSService"\` => \`Sid = "AllowSecretsManagerService"
        Effect = "Allow"
        Principal = {
          Service = "secretsmanager.amazonaws.com"
        }
        Action = [
          "kms:Encrypt",
          "kms:Decrypt",
          "kms:GenerateDataKey*",
          "kms:DescribeKey"
        ]
        Resource = "*"
      },
      {
        Sid    = "AllowRDSService"\``),
  );

  // The handlers connect with admin credentials, so they bypass the proxy.
  if (
    !(await matchGritQL(
      tree,
      TERRAFORM_AURORA_FILE,
      hcl('`output "writer_endpoint" { $_ }`'),
    ))
  ) {
    await applyGritQL(
      tree,
      TERRAFORM_AURORA_FILE,
      hcl(`\`output "reader_endpoint" { $props }\` => \`output "writer_endpoint" {
  description = "Writer endpoint of the Aurora cluster itself, bypassing the RDS Proxy. Used by the admin-credentialled handlers, which connect directly to the cluster."
  value       = aws_rds_cluster.database.endpoint
}

output "reader_endpoint" {
  $props
}\``),
    );
  }

  // The rotation Lambda was the only consumer of lambda_subnet_ids here.
  await applyGritQL(
    tree,
    TERRAFORM_AURORA_FILE,
    hcl('`variable "lambda_subnet_ids" { $_ }` => ``'),
  );
  await applyGritQL(
    tree,
    TERRAFORM_AURORA_FILE,
    hcl('`variable "enable_credential_rotation" { $_ }` => ``'),
  );
};

const migrateAppModule = async (
  tree: Tree,
  filePath: string,
  nextSteps: string[],
): Promise<void> => {
  // Already migrated.
  if (await matchGritQL(tree, filePath, hcl('`DATABASE_HOST = $_`'))) {
    return;
  }

  if (
    !(await matchGritQL(
      tree,
      filePath,
      hcl('`DATABASE_SECRET_ARN = module.aurora.secret_arn`'),
    ))
  ) {
    nextSteps.push(appModuleDivergedMessage(filePath));
    return;
  }

  // A managed secret carries no connection details, so pass them explicitly.
  await applyGritQL(
    tree,
    filePath,
    hcl(
      '`DATABASE_SECRET_ARN = module.aurora.secret_arn` => `DATABASE_SECRET_ARN = module.aurora.secret_arn\n      DATABASE_HOST       = module.aurora.writer_endpoint\n      DATABASE_PORT       = module.aurora.cluster_port\n      DATABASE_NAME       = module.aurora.database_name`',
    ),
  );

  // The core module no longer takes these — RDS owns rotation now.
  await applyGritQL(
    tree,
    filePath,
    hcl('`enable_credential_rotation = var.enable_credential_rotation` => ``'),
  );
  await applyGritQL(
    tree,
    filePath,
    hcl('`variable "enable_credential_rotation" { $_ }` => ``'),
  );
  await applyGritQL(
    tree,
    filePath,
    hcl('`lambda_subnet_ids = var.lambda_subnet_ids` => ``'),
  );
};

export default async function migration(
  tree: Tree,
): Promise<MigrationReturnObject> {
  const nextSteps: string[] = [];

  if (tree.exists(TERRAFORM_AURORA_FILE)) {
    await migrateCoreModule(tree, nextSteps);
  }

  if (tree.exists(TERRAFORM_DBS_DIR)) {
    for (const dirName of tree.children(TERRAFORM_DBS_DIR)) {
      const filePath = joinPathFragments(
        TERRAFORM_DBS_DIR,
        dirName,
        `${dirName}.tf`,
      );
      if (tree.exists(filePath)) {
        await migrateAppModule(tree, filePath, nextSteps);
      }
    }
  }

  await formatFilesInSubtree(tree);

  return { nextSteps };
}
