/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import {
  getProjects,
  joinPathFragments,
  type MigrationReturnObject,
  type Tree,
} from '@nx/devkit';
import { LAMBDA_FUNCTION_GENERATOR_INFO } from '../../../py/lambda-function/generator.js';
import { applyGritQL, matchGritQL } from '../../../utils/ast.js';
import { formatFilesInSubtree } from '../../../utils/format.js';
import type { ComponentMetadata } from '../../../utils/nx.js';

/**
 * Wire powertools Lambda context injection and the cold start metric into
 * handlers generated by py#lambda-function.
 *
 * `@logger.inject_lambda_context` is what annotates each log record with the
 * function name, request id, memory size and cold start flag, and
 * `capture_cold_start_metric` is what emits the `ColdStart` metric.
 *
 * Both rewrites are scoped to the decorator list of the `lambda_handler`
 * definition, so a `@metrics.log_metrics` decorating another function in the
 * same module is left alone.
 */
const INJECT_CONTEXT = '@logger.inject_lambda_context';
const LOG_METRICS_OLD = '@metrics.log_metrics';
const LOG_METRICS_NEW = '@metrics.log_metrics(capture_cold_start_metric=True)';

const HANDLER_DECORATORS = (body: string) => `language python
decorated_definition($decorators, $definition) where {
  $definition <: contains \`lambda_handler\`,
  ${body}
}`;

/** The shape the generator produces: a bare `log_metrics` below the tracer. */
const GENERATED_SHAPE =
  HANDLER_DECORATORS(`$decorators <: contains \`@tracer.capture_lambda_handler\`,
  $decorators <: contains \`${LOG_METRICS_OLD}\``);

const ALREADY_MIGRATED =
  HANDLER_DECORATORS(`$decorators <: contains \`${INJECT_CONTEXT}\`,
  $decorators <: contains \`${LOG_METRICS_NEW}\``);

const REWRITE =
  HANDLER_DECORATORS(`$decorators <: contains \`@tracer.capture_lambda_handler\` => raw\`@tracer.capture_lambda_handler
${INJECT_CONTEXT}\`,
  $decorators <: contains \`${LOG_METRICS_OLD}\` => \`${LOG_METRICS_NEW}\``);

const migrateHandler = async (
  tree: Tree,
  handlerPath: string,
  nextSteps: string[],
): Promise<void> => {
  if (!tree.exists(handlerPath)) return;

  if (await matchGritQL(tree, handlerPath, ALREADY_MIGRATED)) return;

  if (!(await matchGritQL(tree, handlerPath, GENERATED_SHAPE))) {
    nextSteps.push(
      `${handlerPath}: diverged from the generated py#lambda-function shape - left untouched. To annotate logs with the Lambda context and emit a ColdStart metric, add \`${INJECT_CONTEXT}\` to the handler and change \`${LOG_METRICS_OLD}\` to \`${LOG_METRICS_NEW}\`.`,
    );
    return;
  }

  await applyGritQL(tree, handlerPath, REWRITE);
};

export default async function migration(
  tree: Tree,
): Promise<MigrationReturnObject> {
  const nextSteps: string[] = [];

  for (const project of getProjects(tree).values()) {
    const components = (
      (project.metadata as { components?: ComponentMetadata[] })?.components ??
      []
    ).filter(
      (component) => component.generator === LAMBDA_FUNCTION_GENERATOR_INFO.id,
    );

    for (const component of components) {
      if (!component.path) continue;
      await migrateHandler(
        tree,
        joinPathFragments(project.root, component.path),
        nextSteps,
      );
    }
  }

  await formatFilesInSubtree(tree);

  return { nextSteps };
}
