/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import {
  generateFiles,
  joinPathFragments,
  OverwriteStrategy,
  type ProjectConfiguration,
  type Tree,
  updateJson,
} from '@nx/devkit';
import { addStarExport } from '../ast';
import type { Iac } from '../iac';
import { esmVars } from '../module-format';
import { addDependencyToTargetIfNotPresent } from '../nx';
import {
  PACKAGES_DIR,
  SHARED_CONSTRUCTS_DIR,
  SHARED_TERRAFORM_DIR,
} from '../shared-constructs-constants';
import { terraformProviderVersions } from '../versions';

/**
 * The DCR proxy Lambda handlers. Each is bundled independently and wired to a
 * dedicated route on the HTTP API.
 */
export const DCR_PROXY_HANDLERS = [
  'authorization-server-metadata',
  'authorize',
  'mcp-proxy',
  'protected-resource-metadata',
  'register',
  'token',
] as const;

export type DcrProxyHandler = (typeof DCR_PROXY_HANDLERS)[number];

export interface AddDcrProxyInfraProps {
  dcrProxyNameClassName: string;
  dcrProxyNameKebabCase: string;

  /**
   * Fully qualified name of the TypeScript project that owns the bundled
   * handlers, used to wire the shared package build to depend on it.
   */
  proxyProjectName: string;

  /**
   * Map of handler name to the workspace-root-relative path of its bundle
   * output directory (e.g. `dist/packages/dcr-proxy/bundle/token`).
   */
  bundlePathsFromRoot: Record<DcrProxyHandler, string>;

  iac: Iac;
}

/**
 * Add a DCR proxy infrastructure (CDK construct or Terraform module) to the
 * relevant shared package.
 *
 * The infrastructure exposes props/variables for the caller to inject their
 * Cognito identifiers and the upstream MCP server URL from their own stack,
 * since these may or may not be generated by this plugin. The Lambda handlers
 * live in a standalone TypeScript project and are bundled by rolldown; both
 * IaC providers reference the same bundle output.
 */
export const addDcrProxyInfra = async (
  tree: Tree,
  options: AddDcrProxyInfraProps,
) => {
  if (options.iac === 'cdk') {
    await addDcrProxyCdkConstructs(tree, options);
  } else if (options.iac === 'terraform') {
    addDcrProxyTerraformModules(tree, options);
  } else {
    throw new Error(`Unsupported iac ${options.iac}`);
  }

  // Ensure the handler bundles are built before the shared package
  updateJson(
    tree,
    joinPathFragments(
      PACKAGES_DIR,
      options.iac === 'cdk' ? SHARED_CONSTRUCTS_DIR : SHARED_TERRAFORM_DIR,
      'project.json',
    ),
    (config: ProjectConfiguration) => {
      addDependencyToTargetIfNotPresent(
        config,
        'build',
        `${options.proxyProjectName}:build`,
      );
      return config;
    },
  );
};

/**
 * Add the DCR proxy CDK construct to the shared constructs package.
 */
const addDcrProxyCdkConstructs = async (
  tree: Tree,
  options: AddDcrProxyInfraProps,
) => {
  // Ensure the core HTTP API construct + utils are available (the proxy reuses
  // them). These are shared with the api generators and safe to (re)generate
  // with KeepExisting.
  for (const coreApiFile of ['http', 'utils']) {
    generateFiles(
      tree,
      joinPathFragments(
        import.meta.dirname,
        '..',
        'api-constructs',
        'files',
        'cdk',
        'core',
        'api',
        coreApiFile,
      ),
      joinPathFragments(
        PACKAGES_DIR,
        SHARED_CONSTRUCTS_DIR,
        'src',
        'core',
        'api',
      ),
      { ...esmVars(tree) },
      {
        overwriteStrategy: OverwriteStrategy.KeepExisting,
      },
    );
  }

  generateFiles(
    tree,
    joinPathFragments(
      import.meta.dirname,
      'files',
      'cdk',
      'app',
      'dcr-proxies',
    ),
    joinPathFragments(
      PACKAGES_DIR,
      SHARED_CONSTRUCTS_DIR,
      'src',
      'app',
      'dcr-proxies',
    ),
    {
      nameClassName: options.dcrProxyNameClassName,
      nameKebabCase: options.dcrProxyNameKebabCase,
      bundlePathsFromRoot: options.bundlePathsFromRoot,
      ...esmVars(tree),
    },
    {
      overwriteStrategy: OverwriteStrategy.KeepExisting,
    },
  );

  // Export the construct
  await addStarExport(
    tree,
    joinPathFragments(
      PACKAGES_DIR,
      SHARED_CONSTRUCTS_DIR,
      'src',
      'app',
      'dcr-proxies',
      'index.ts',
    ),
    `./${options.dcrProxyNameKebabCase}/${options.dcrProxyNameKebabCase}.js`,
  );
  await addStarExport(
    tree,
    joinPathFragments(
      PACKAGES_DIR,
      SHARED_CONSTRUCTS_DIR,
      'src',
      'app',
      'index.ts',
    ),
    './dcr-proxies/index.js',
  );
};

/**
 * Add the DCR proxy Terraform module to the shared terraform package.
 */
const addDcrProxyTerraformModules = (
  tree: Tree,
  options: AddDcrProxyInfraProps,
) => {
  // Ensure the core HTTP API module is available (the proxy reuses it). This is
  // shared with the api generators and safe to (re)generate with KeepExisting.
  generateFiles(
    tree,
    joinPathFragments(
      import.meta.dirname,
      '..',
      'api-constructs',
      'files',
      'terraform',
      'core',
      'api',
      'http',
    ),
    joinPathFragments(PACKAGES_DIR, SHARED_TERRAFORM_DIR, 'src', 'core', 'api'),
    { ...terraformProviderVersions() },
    {
      overwriteStrategy: OverwriteStrategy.KeepExisting,
    },
  );

  // Generate the app specific terraform module
  generateFiles(
    tree,
    joinPathFragments(
      import.meta.dirname,
      'files',
      'terraform',
      'app',
      'dcr-proxies',
    ),
    joinPathFragments(
      PACKAGES_DIR,
      SHARED_TERRAFORM_DIR,
      'src',
      'app',
      'dcr-proxies',
    ),
    {
      nameClassName: options.dcrProxyNameClassName,
      nameKebabCase: options.dcrProxyNameKebabCase,
      bundlePathsFromRoot: options.bundlePathsFromRoot,
      ...terraformProviderVersions(),
    },
    {
      overwriteStrategy: OverwriteStrategy.KeepExisting,
    },
  );
};
