/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import {
  addDependenciesToPackageJson,
  generateFiles,
  joinPathFragments,
  OverwriteStrategy,
  type Tree,
} from '@nx/devkit';
import { addStarExport } from '../ast';
import {
  PACKAGES_DIR,
  SHARED_CONSTRUCTS_DIR,
} from '../shared-constructs-constants';
import { withVersions } from '../versions';

export interface AddDcrProxyInfraProps {
  dcrProxyNameClassName: string;
  dcrProxyNameKebabCase: string;
}

/**
 * Add a DCR proxy CDK construct to the shared constructs package.
 *
 * The construct exposes props for the caller to inject their Cognito
 * UserPool/UserPoolClient/UserPoolDomain and the upstream MCP server URL from
 * their own stack, since these may or may not be generated by this plugin.
 */
export const addDcrProxyInfra = async (
  tree: Tree,
  options: AddDcrProxyInfraProps,
) => {
  // Generate the app specific DCR proxy construct (+ its Lambda handlers)
  generateFiles(
    tree,
    joinPathFragments(
      import.meta.dirname,
      'files',
      'cdk',
      'app',
      'dcr-proxies',
    ),
    joinPathFragments(
      PACKAGES_DIR,
      SHARED_CONSTRUCTS_DIR,
      'src',
      'app',
      'dcr-proxies',
    ),
    {
      nameClassName: options.dcrProxyNameClassName,
      nameKebabCase: options.dcrProxyNameKebabCase,
    },
    {
      overwriteStrategy: OverwriteStrategy.KeepExisting,
    },
  );

  // Export the construct
  await addStarExport(
    tree,
    joinPathFragments(
      PACKAGES_DIR,
      SHARED_CONSTRUCTS_DIR,
      'src',
      'app',
      'dcr-proxies',
      'index.ts',
    ),
    `./${options.dcrProxyNameKebabCase}/${options.dcrProxyNameKebabCase}.js`,
  );
  await addStarExport(
    tree,
    joinPathFragments(
      PACKAGES_DIR,
      SHARED_CONSTRUCTS_DIR,
      'src',
      'app',
      'index.ts',
    ),
    './dcr-proxies/index.js',
  );

  // The Lambda handlers are TypeScript, bundled at synth time by the
  // NodejsFunction (esbuild). They live under the constructs package src, so
  // its tsc build type-checks them too — hence @types/aws-lambda (dev) and the
  // token handler's @aws-sdk/client-secrets-manager import (runtime, provided
  // by the Lambda runtime but needed for type-checking and local dev).
  addDependenciesToPackageJson(
    tree,
    withVersions(['@aws-sdk/client-secrets-manager']),
    withVersions(['@types/aws-lambda']),
  );
};
