/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import type { AllowlistEntry } from './types';

export const PRE_APPROVED_LICENSES: AllowlistEntry[] = [
  {
    spdxId: '0BSD',
    fullName: 'BSD Zero Clause License',
    aliases: ['Zero-Clause BSD (0BSD)'],
  },
  {
    spdxId: 'AFL-2.1',
    fullName: 'Academic Free License v2.1',
    aliases: ['Academic Free 2.1'],
  },
  {
    spdxId: 'AFL-3.0',
    fullName: 'Academic Free License v3.0',
    aliases: ['Academic Free 3.0', 'Academic Free License, version 3'],
  },
  {
    spdxId: 'Apache-1.1',
    fullName: 'Apache License 1.1',
    aliases: [
      'ASL 1.1',
      'Apache v1.1',
      'Apache Software License, version 1.1',
      'The Apache Software License, Version 1.1',
      'The OpenSymphony Software License 1.1',
      'The HtmlUnit Software License',
      'MX4J',
      'MX4J License',
    ],
  },
  {
    spdxId: 'Apache-2.0',
    fullName: 'Apache License 2.0',
    aliases: [
      'Apache v2.0',
      'Apache 2.0',
      'Apache 2',
      'Apache v2',
      'Apache v2 License',
      'APACHE2',
      'APACHE-2',
      'Apache2.0',
      'The Apache Software License, Version 2.0',
      'Apache License, Version 2.0',
      'Apache Licence, Version 2.0',
      'Apache License Version 2.0',
      'Apache Licence 2.0',
      'Apache License 2.0',
      'Apache License v2',
      'Apache Version 2.0',
      'Apache, Version 2.0',
      'Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)',
      'Apache 2.0 License',
      'Apache-2.0 license',
      'Apache Software License 2.0',
      'Apache2',
      'ASF 2.0',
      'The Apache License, Version 2.0',
      'Apache Software License - Version 2.0',
      'http://www.apache.org/licenses/LICENSE-2.0',
      'The Apache 2.0 License',
      'the Apache License, ASL Version 2.0',
      'Apache-2.0.',
      'Apache Public License 2.0',
      'Apache License v2.0',
      'Apache License, 2.0',
      'Apache 2 License',
      'Apache 2.0 Software License',
      'Apache License 2',
      'Apache Software License, version 2.0',
      'Apache License Version 2',
      'The Apache License 2.0',
      'ApacheV2.0',
      'ASL 2.0',
      'ASL2.0',
      'Apache License (2.0)',
      'Apache License,Version 2.0',
      'Apache-2.0 AND MIT',
      'MIT AND Apache-2.0',
      'Apache 2.0 (http://www.apache.org/licenses/LICENSE-2.0)',
      'TOMORROW OPEN SOURCE TECHNOLOGY LICENSE 1.0',
      'TOST-1.0',
      'MIT -or- Apache License 2.0',
      'Scala License',
      'Scala',
      'MIT/Apache-2.0',
      'Apache Software License (Apache 2.0)',
      'Apache-2.0 OR MIT',
      'MIT or Apache-2.0',
      'Apache License 2.0.',
      'Apache Software License v2.0',
      'Apache License - v2.0',
      'Dual License',
    ],
  },
  {
    spdxId: 'Apache-2.0 WITH LLVM-exception',
    fullName: 'Apache License 2.0 with LLVM Exception',
    aliases: [],
  },
  {
    spdxId: 'blessing',
    fullName: 'SQLite Blessing',
    aliases: [],
  },
  {
    spdxId: 'BSD-2-Clause',
    fullName: 'BSD 2-clause "Simplified" License',
    aliases: [
      'BSD2',
      'BSD-2',
      'BSD 2',
      'BSD 2.0',
      'BSD 2-Clause',
      'BSD 2 Clause',
      'BSD-Clause-2',
      'BSD 2-Clause License',
      'BSD (2 clause)',
      '2-clause BSD',
      'Two-clause BSD License',
      'Two clause BSD License',
      '2-clause BSD licence (Simplified BSD) Licence',
      'Simplified BSD License',
      'Simplified BSD',
      '2-clause BSD license',
      'BSD-2 License',
      'The BSD 2-Clause License',
      'BSD (2-clause)',
      'Two-clause BSD-style license',
      'The 2-Clause BSD License',
      'Carnegie Mellon Dictionary',
    ],
  },
  {
    spdxId: 'BSD-2-Clause-Patent',
    fullName: 'BSD-2-Clause Plus Patent License',
    aliases: ['BSD+Patent'],
  },
  {
    spdxId: 'BSD-3-Clause',
    fullName: 'BSD 3-clause "New" or "Revised" License',
    aliases: [
      '3-clause BSD',
      '3-Clause BSD License',
      'BSD-new',
      'BSD3',
      'BSD-3',
      'BSD 3',
      'BSD 3.0',
      'BSD 3-Clause',
      'BSD (3 Clause)',
      'BSD(3-clause)',
      'BSD 3-Clause License',
      'BSD 3-Clause "New" License',
      'BSD 3-clause New License',
      'New BSD',
      'New BSD License',
      'BSD License 3',
      'The BSD 3-Clause License',
      'BSD 3-Clause "New" or "Revised" License (BSD-3-Clause)',
      'The BSD 3-Clause License (BSD3)',
      'Eclipse Distribution License - v 1.0',
      'Eclipse Distribution License v. 1.0',
      'Eclipse Distribution License v1.0',
      'EDL 1.0',
      'Eclipse Distribution License (New BSD License)',
      'BSD 3 Clause',
      'New BSD (3-clause) License',
      'BSD Licence 3',
      'Three-clause BSD-style',
      'New BSD (3-clause) License',
      'BSD New',
      'BSD (3-clause)',
      'BSD (3 clauses)',
      'The BSD3 License',
      'Trilead Library License (BSD-Like)',
      'Sequence Library License (BSD-like)',
      'The 3-Clause BSD License',
      'BSD-3-Clause-License',
      'The New BSD License',
      'Revised BSD License',
      'HSQLDB License, a BSD open source license',
      'Aduna BSD license',
      'BSD 3 Clause License',
      'jMock',
      'JiBX',
      'three-clause BSD',
    ],
  },
  {
    spdxId: 'BSL-1.0',
    fullName: 'Boost Software License 1.0',
    aliases: ['Boost', 'BSL1.0', 'BSL'],
  },
  {
    spdxId: 'CC-BY-2.0',
    fullName: 'Creative Commons Attribution 2.0',
    aliases: [],
  },
  {
    spdxId: 'CC-BY-2.5',
    fullName: 'Creative Commons Attribution 2.5',
    aliases: [],
  },
  {
    spdxId: 'CC-BY-3.0',
    fullName: 'Creative Commons Attribution 3.0',
    aliases: [],
  },
  {
    spdxId: 'CC-BY-4.0',
    fullName: 'Creative Commons Attribution 4.0',
    aliases: [],
  },
  {
    spdxId: 'CC-PDDC',
    fullName: 'Creative Commons Public Domain Dedication and Certification',
    aliases: [],
  },
  {
    spdxId: 'CC0-1.0',
    fullName: 'Creative Commons Zero v1.0 Universal',
    aliases: [
      'Creative Commons Copyright-Only Dedication',
      'CC0',
      'CC0 1.0',
      'Creative Commons 1.0 Universal (Public Domain Dedication)',
      'CC0 1.0 Universal',
      'CC0 Universal',
      'CC-0',
    ],
  },
  {
    spdxId: 'curl',
    fullName: 'curl License',
    aliases: [],
  },
  {
    spdxId: 'FTL',
    fullName: 'Freetype Project License',
    aliases: ['FreeType'],
  },
  {
    spdxId: 'ICU',
    fullName: 'ICU License',
    aliases: ['Unicode/ICU License'],
  },
  {
    spdxId: 'IJG',
    fullName: 'Independent JPEG Group License',
    aliases: ['JPEG License'],
  },
  {
    spdxId: 'ImageMagick',
    fullName: 'ImageMagick License',
    aliases: ['ImageMagick'],
  },
  {
    spdxId: 'ISC',
    fullName: 'ISC License',
    aliases: ['ISC', 'ISC License (ISCL)'],
  },
  {
    spdxId: 'LicenseRef-scancode-amazon-sl',
    fullName: 'Amazon Software License',
    aliases: ['LicenseRef-.amazon.com.-AmznSL-1.0'],
  },
  {
    spdxId: 'MIT',
    fullName: 'MIT License',
    aliases: [
      'MIT',
      'MIT License',
      'MIT Licence',
      'The MIT License',
      'MIT (LICENSE)',
      'MIT(LICENSE)',
      'The MIT License (MIT)',
      'Expat License',
      'The Expat License',
      'Bouncy Castle Licence',
      'MIT/X11',
      'MIT X11 License',
      '(MIT)',
      'The MIT License: http://www.opensource.org/licenses/mit-license.php',
      'MIT license',
      'MIT-License',
      'License :: OSI Approved :: MIT License',
      'MIT (https://opensource.org/licenses/MIT)',
      'SLF4J',
      'Expat',
    ],
  },
  {
    spdxId: 'MIT-CMU',
    fullName: 'CMU License',
    aliases: [],
  },
  {
    spdxId: 'MulanPSL-2.0',
    fullName: 'Mulan Permissive Software License, Version 2',
    aliases: ['MulanPSL2'],
  },
  {
    spdxId: 'OFL-1.0',
    fullName: 'SIL Open Font License 1.0',
    aliases: ['SIL OPEN FONT LICENSE', 'Font Awesome Free'],
  },
  {
    spdxId: 'OFL-1.1',
    fullName: 'SIL Open Font License 1.1',
    aliases: [],
  },
  {
    spdxId: 'OLDAP-2.8',
    fullName: 'Open LDAP Public License v2.8',
    aliases: ['OpenLDAP'],
  },
  {
    spdxId: 'OpenSSL',
    fullName: 'OpenSSL License',
    aliases: ['OpenSSL'],
  },
  {
    spdxId: 'PDDL-1.0',
    fullName: 'ODC Public Domain Dedication & License 1.0',
    aliases: ['PDDL (Public Domain Dedication and License)'],
  },
  {
    spdxId: 'PHP-3.0',
    fullName: 'PHP License v3.0',
    aliases: ['PHP'],
  },
  {
    spdxId: 'PHP-3.01',
    fullName: 'PHP LIcense v3.01',
    aliases: [],
  },
  {
    spdxId: 'PostgreSQL',
    fullName: 'PostgreSQL License',
    aliases: ['PostgreSQL'],
  },
  {
    spdxId: 'PSF-2.0',
    fullName: 'Python Software Foundation License 2.0',
    aliases: [
      'PSF',
      'Python Software Foundation License',
      'PSF License',
      'PSFL',
      'PSFL 2',
      'PSF 2.0',
      'Python Software Foundation License v 2.1.1',
      'Python v2.1.1',
      'Python Software Foundation License Version 2',
    ],
  },
  {
    spdxId: 'Python-2.0',
    fullName: 'Python License 2.0',
    aliases: [],
  },
  {
    spdxId: 'Python-2.0.1',
    fullName: 'Python License 2.0.1',
    aliases: [],
  },
  {
    spdxId: 'Ruby',
    fullName: 'Ruby License',
    aliases: ['Ruby'],
  },
  {
    spdxId: 'Unlicense',
    fullName: 'Unlicense',
    aliases: ['unlicense.org', 'The Unlicense', 'The Unlicense (Unlicense)'],
  },
  {
    spdxId: 'WTFPL',
    fullName: 'Do What The F*ck You Want To Public License',
    aliases: ['WTFPL2'],
  },
  {
    spdxId: 'X11',
    fullName: 'X11 License',
    aliases: [],
  },
  {
    spdxId: 'Zlib',
    fullName: 'zlib License',
    aliases: [
      'Zlib/libpng',
      'zlib',
      'The zlib/libpng License',
      'The zlib/libpng License (Zlib)',
      'Zlib/PNG License',
    ],
  },
];
