/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import type { AllowlistEntry } from './types';

export const PRE_APPROVED_LICENSES: AllowlistEntry[] = [
  {
    spdxId: '0BSD',
    fullName: 'BSD Zero Clause License',
    aliases: ['Zero-Clause BSD (0BSD)'],
  },
  {
    spdxId: 'AFL-2.1',
    fullName: 'Academic Free License v2.1',
    aliases: ['Academic Free 2.1'],
  },
  {
    spdxId: 'AFL-3.0',
    fullName: 'Academic Free License v3.0',
    aliases: ['Academic Free 3.0', 'Academic Free License, version 3'],
  },
  { spdxId: 'AMD-newlib', fullName: 'AMD newlib License', aliases: [] },
  {
    spdxId: 'AML',
    fullName: 'Apple MIT License',
    aliases: ['Apple Sample Code License'],
  },
  {
    spdxId: 'AML-glslang',
    fullName: 'AML glslang variant License',
    aliases: [],
  },
  {
    spdxId: 'ANTLR-PD',
    fullName: 'ANTLR Software Rights Notice',
    aliases: ['ANTLR 2'],
  },
  {
    spdxId: 'ANTLR-PD-fallback',
    fullName: 'ANTLR Software Rights Notice with license fallback',
    aliases: [],
  },
  { spdxId: 'APAFML', fullName: 'Adobe Postscript AFM License', aliases: [] },
  { spdxId: 'AdaCore-doc', fullName: 'AdaCore Doc License', aliases: [] },
  {
    spdxId: 'Adobe-Display-PostScript',
    fullName: 'Adobe Display PostScript License',
    aliases: [],
  },
  { spdxId: 'Adobe-Glyph', fullName: 'Adobe Glyph List License', aliases: [] },
  {
    spdxId: 'Adobe-Utopia',
    fullName: 'Adobe Utopia Font License',
    aliases: [],
  },
  {
    spdxId: 'Apache-1.1',
    fullName: 'Apache License 1.1',
    aliases: [
      'ASL 1.1',
      'Apache v1.1',
      'Apache Software License, version 1.1',
      'The Apache Software License, Version 1.1',
      'The OpenSymphony Software License 1.1',
      'The HtmlUnit Software License',
      'MX4J',
      'MX4J License',
    ],
  },
  {
    spdxId: 'Apache-2.0',
    fullName: 'Apache License 2.0',
    aliases: [
      'Apache v2.0',
      'Apache 2.0',
      'Apache 2',
      'Apache v2',
      'Apache v2 License',
      'APACHE2',
      'APACHE-2',
      'Apache2.0',
      'The Apache Software License, Version 2.0',
      'Apache License, Version 2.0',
      'Apache Licence, Version 2.0',
      'Apache License Version 2.0',
      'Apache Licence 2.0',
      'Apache License 2.0',
      'Apache License v2',
      'Apache Version 2.0',
      'Apache, Version 2.0',
      'Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)',
      'Apache 2.0 License',
      'Apache-2.0 license',
      'Apache Software License 2.0',
      'Apache2',
      'ASF 2.0',
      'The Apache License, Version 2.0',
      'Apache Software License - Version 2.0',
      'http://www.apache.org/licenses/LICENSE-2.0',
      'The Apache 2.0 License',
      'the Apache License, ASL Version 2.0',
      'Apache-2.0.',
      'Apache Public License 2.0',
      'Apache License v2.0',
      'Apache License, 2.0',
      'Apache 2 License',
      'Apache 2.0 Software License',
      'Apache License 2',
      'Apache Software License, version 2.0',
      'Apache License Version 2',
      'The Apache License 2.0',
      'ApacheV2.0',
      'ASL 2.0',
      'ASL2.0',
      'Apache License (2.0)',
      'Apache License,Version 2.0',
      'Apache-2.0 AND MIT',
      'MIT AND Apache-2.0',
      'Apache 2.0 (http://www.apache.org/licenses/LICENSE-2.0)',
      'TOMORROW OPEN SOURCE TECHNOLOGY LICENSE 1.0',
      'TOST-1.0',
      'MIT -or- Apache License 2.0',
      'Scala License',
      'Scala',
      'MIT/Apache-2.0',
      'Apache Software License (Apache 2.0)',
      'Apache-2.0 OR MIT',
      'MIT or Apache-2.0',
      'Apache License 2.0.',
      'Apache Software License v2.0',
      'Apache License - v2.0',
      'Dual License',
    ],
  },
  {
    spdxId: 'Apache-2.0 WITH LLVM-exception',
    fullName: 'Apache License 2.0 with LLVM Exception',
    aliases: [],
  },
  {
    spdxId: 'Artistic-1.0',
    fullName: 'Artistic License 1.0',
    aliases: ['The Artistic License 1.0'],
  },
  {
    spdxId: 'Artistic-1.0-Perl',
    fullName: 'Artistic License 1.0(Perl)',
    aliases: ['Perl Artistic'],
  },
  {
    spdxId: 'Artistic-2.0',
    fullName: 'Artistic License 2.0',
    aliases: ['Artistic 2.0', 'Artistic Licence 2.0'],
  },
  {
    spdxId: 'Artistic-dist',
    fullName: 'Artistic License 1.0 (dist)',
    aliases: [],
  },
  { spdxId: 'BSD-1-Clause', fullName: 'BSD 1-Clause License', aliases: [] },
  {
    spdxId: 'BSD-2-Clause',
    fullName: 'BSD 2-clause "Simplified" License',
    aliases: [
      'BSD2',
      'BSD-2',
      'BSD 2',
      'BSD 2.0',
      'BSD 2-Clause',
      'BSD 2 Clause',
      'BSD-Clause-2',
      'BSD 2-Clause License',
      'BSD (2 clause)',
      '2-clause BSD',
      'Two-clause BSD License',
      'Two clause BSD License',
      '2-clause BSD licence (Simplified BSD) Licence',
      'Simplified BSD License',
      'Simplified BSD',
      '2-clause BSD license',
      'BSD-2 License',
      'The BSD 2-Clause License',
      'BSD (2-clause)',
      'Two-clause BSD-style license',
      'The 2-Clause BSD License',
      'Carnegie Mellon Dictionary',
    ],
  },
  {
    spdxId: 'BSD-2-Clause-Darwin',
    fullName: 'BSD 2-Clause - Ian Darwin variant',
    aliases: [],
  },
  {
    spdxId: 'BSD-2-Clause-FreeBSD',
    fullName: 'BSD 2-clause FreeBSD License',
    aliases: ['FreeBSD License'],
  },
  {
    spdxId: 'BSD-2-Clause-NetBSD',
    fullName: 'BSD 2-clause NetBSD License',
    aliases: [],
  },
  {
    spdxId: 'BSD-2-Clause-Views',
    fullName: 'BSD 2-Clause with views sentence',
    aliases: [],
  },
  {
    spdxId: 'BSD-2-Clause-first-lines',
    fullName: 'BSD 2-Clause - first lines requirement',
    aliases: [],
  },
  {
    spdxId: 'BSD-2-Clause-pkgconf-disclaimer',
    fullName: 'BSD 2-Clause pkgconf disclaimer variant',
    aliases: [],
  },
  {
    spdxId: 'BSD-3-Clause',
    fullName: 'BSD 3-clause "New" or "Revised" License',
    aliases: [
      '3-clause BSD',
      '3-Clause BSD License',
      'BSD-new',
      'BSD3',
      'BSD-3',
      'BSD 3',
      'BSD 3.0',
      'BSD 3-Clause',
      'BSD (3 Clause)',
      'BSD(3-clause)',
      'BSD 3-Clause License',
      'BSD 3-Clause "New" License',
      'BSD 3-clause New License',
      'New BSD',
      'New BSD License',
      'BSD License 3',
      'The BSD 3-Clause License',
      'BSD 3-Clause "New" or "Revised" License (BSD-3-Clause)',
      'The BSD 3-Clause License (BSD3)',
      'Eclipse Distribution License - v 1.0',
      'Eclipse Distribution License v. 1.0',
      'Eclipse Distribution License v1.0',
      'EDL 1.0',
      'Eclipse Distribution License (New BSD License)',
      'BSD 3 Clause',
      'New BSD (3-clause) License',
      'BSD Licence 3',
      'Three-clause BSD-style',
      'New BSD (3-clause) License',
      'BSD New',
      'BSD (3-clause)',
      'BSD (3 clauses)',
      'The BSD3 License',
      'Trilead Library License (BSD-Like)',
      'Sequence Library License (BSD-like)',
      'The 3-Clause BSD License',
      'BSD-3-Clause-License',
      'The New BSD License',
      'Revised BSD License',
      'HSQLDB License, a BSD open source license',
      'Aduna BSD license',
      'BSD 3 Clause License',
      'jMock',
      'JiBX',
      'three-clause BSD',
    ],
  },
  {
    spdxId: 'BSD-3-Clause-Attribution',
    fullName: 'BSD with attribution',
    aliases: [],
  },
  {
    spdxId: 'BSD-3-Clause-HP',
    fullName: 'Hewlett-Packard BSD variant license',
    aliases: [],
  },
  {
    spdxId: 'BSD-3-Clause-LBNL',
    fullName: 'Lawrence Berkeley National Labs BSD variant license',
    aliases: [],
  },
  {
    spdxId: 'BSD-3-Clause-Modification',
    fullName: 'BSD 3-Clause Modification',
    aliases: [],
  },
  {
    spdxId: 'BSD-3-Clause-Open-MPI',
    fullName: 'BSD 3-Clause Open MPI variant',
    aliases: [],
  },
  {
    spdxId: 'BSD-3-Clause-Sun',
    fullName: 'BSD 3-Clause Sun Microsystems',
    aliases: [],
  },
  {
    spdxId: 'BSD-3-Clause-acpica',
    fullName: 'BSD 3-Clause acpica variant',
    aliases: [],
  },
  {
    spdxId: 'BSD-3-Clause-flex',
    fullName: 'BSD 3-Clause Flex variant',
    aliases: [],
  },
  { spdxId: 'BSD-4.3RENO', fullName: 'BSD 4.3 RENO License', aliases: [] },
  {
    spdxId: 'BSD-Source-Code',
    fullName: 'BSD Source Code Attribution',
    aliases: [],
  },
  {
    spdxId: 'BSD-Source-beginning-file',
    fullName: 'BSD Source Code Attribution - beginning of file variant',
    aliases: [],
  },
  {
    spdxId: 'BSL-1.0',
    fullName: 'Boost Software License 1.0',
    aliases: ['Boost', 'BSL1.0', 'BSL'],
  },
  { spdxId: 'Baekmuk', fullName: 'Baekmuk License', aliases: [] },
  { spdxId: 'Beerware', fullName: 'Beerware License', aliases: [] },
  {
    spdxId: 'Bitstream-Charter',
    fullName: 'Bitstream Charter Font License',
    aliases: [],
  },
  {
    spdxId: 'Bitstream-Vera',
    fullName: 'Bitstream Vera Font License',
    aliases: [],
  },
  {
    spdxId: 'BlueOak-1.0.0',
    fullName: 'Blue Oak Model License 1.0.0',
    aliases: [],
  },
  {
    spdxId: 'Boehm-GC',
    fullName: 'Boehm-Demers-Weiser GC License',
    aliases: [],
  },
  {
    spdxId: 'Boehm-GC-without-fee',
    fullName: 'Boehm-Demers-Weiser GC License (without fee)',
    aliases: [],
  },
  {
    spdxId: 'Brian-Gladman-2-Clause',
    fullName: 'Brian Gladman 2-Clause License',
    aliases: [],
  },
  {
    spdxId: 'Brian-Gladman-3-Clause',
    fullName: 'Brian Gladman 3-Clause License',
    aliases: [],
  },
  {
    spdxId: 'CC-BY-2.0',
    fullName: 'Creative Commons Attribution 2.0',
    aliases: [],
  },
  {
    spdxId: 'CC-BY-2.5',
    fullName: 'Creative Commons Attribution 2.5',
    aliases: [],
  },
  {
    spdxId: 'CC-BY-2.5-AU',
    fullName: 'Creative Commons Attribution 2.5 Australia',
    aliases: [],
  },
  {
    spdxId: 'CC-BY-3.0',
    fullName: 'Creative Commons Attribution 3.0',
    aliases: [],
  },
  {
    spdxId: 'CC-BY-3.0-AU',
    fullName: 'Creative Commons Attribution 3.0 Australia',
    aliases: [],
  },
  {
    spdxId: 'CC-BY-3.0-IGO',
    fullName: 'Creative Commons Attribution 3.0 IGO',
    aliases: [],
  },
  {
    spdxId: 'CC-BY-3.0-US',
    fullName: 'Creative Commons Attribution 3.0 United States',
    aliases: [],
  },
  {
    spdxId: 'CC-BY-4.0',
    fullName: 'Creative Commons Attribution 4.0',
    aliases: [],
  },
  {
    spdxId: 'CC-PDDC',
    fullName: 'Creative Commons Public Domain Dedication and Certification',
    aliases: [],
  },
  {
    spdxId: 'CC0-1.0',
    fullName: 'Creative Commons Zero v1.0 Universal',
    aliases: [
      'Creative Commons Copyright-Only Dedication',
      'CC0',
      'CC0 1.0',
      'Creative Commons 1.0 Universal (Public Domain Dedication)',
      'CC0 1.0 Universal',
      'CC0 Universal',
      'CC-0',
    ],
  },
  {
    spdxId: 'CDDL-1.0',
    fullName: 'Common Development and Distribution License 1.0',
    aliases: [
      'Common Development and Distribution License (CDDL) v1.0',
      'COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0',
      'CDDL 1.0',
    ],
  },
  {
    spdxId: 'CDDL-1.1',
    fullName: 'Common Development and Distribution License 1.1',
    aliases: ['CDDL 1.1'],
  },
  { spdxId: 'CFITSIO', fullName: 'CFITSIO License', aliases: [] },
  {
    spdxId: 'CMU-Mach-nodoc',
    fullName: 'CMU Mach - no notices-in-documentation variant',
    aliases: [],
  },
  {
    spdxId: 'CNRI-Jython',
    fullName: 'CNRI Jython License',
    aliases: ['Jython', 'Jython License'],
  },
  { spdxId: 'CNRI-Python', fullName: 'CNRI Python License', aliases: [] },
  {
    spdxId: 'CPOL-1.02',
    fullName: 'Code Project Open License 1.02',
    aliases: [],
  },
  { spdxId: 'Clips', fullName: 'Clips License', aliases: [] },
  {
    spdxId: 'Cornell-Lossless-JPEG',
    fullName: 'Cornell Lossless JPEG License',
    aliases: [],
  },
  { spdxId: 'Cronyx', fullName: 'Cronyx License', aliases: [] },
  { spdxId: 'CryptoSwift', fullName: 'CryptoSwift License', aliases: [] },
  { spdxId: 'DEC-3-Clause', fullName: 'DEC 3-Clause License', aliases: [] },
  { spdxId: 'DocBook-DTD', fullName: 'DocBook DTD License', aliases: [] },
  { spdxId: 'DocBook-Schema', fullName: 'DocBook Schema License', aliases: [] },
  {
    spdxId: 'DocBook-Stylesheet',
    fullName: 'DocBook Stylesheet License',
    aliases: [],
  },
  { spdxId: 'DocBook-XML', fullName: 'DocBook XML License', aliases: [] },
  {
    spdxId: 'EFL-2.0',
    fullName: 'Eiffel Forum License v2.0',
    aliases: ['Eiffel Forum License 2.0'],
  },
  {
    spdxId: 'EPL-1.0',
    fullName: 'Eclipse Public License 1.0',
    aliases: [
      'Eclipse Public License',
      'Eclipse Public License, Version 1.0',
      'Eclipse Public License v1.0',
      'Eclipse Public License - Version 1.0',
      'Eclipse Public License - v 1.0',
      'The Eclipse Public License Version 1.0',
      'Eclipse Public License (EPL), Version 1.0',
    ],
  },
  {
    spdxId: 'EPL-2.0',
    fullName: 'Eclipse Public License 2.0',
    aliases: [
      'Eclipse Public License v2.0',
      'Eclipse Public License v. 2.0',
      'The Eclipse Public License Version 2.0',
      'Eclipse Public License, Version 2.0',
      'Eclipse Public License - v 2.0',
      'Eclipse Public License - Version 2.0',
      'EPL 2.0',
    ],
  },
  { spdxId: 'Entessa', fullName: 'Entessa Public License v1.0', aliases: [] },
  { spdxId: 'FBM', fullName: 'Fuzzy Bitmap License', aliases: [] },
  { spdxId: 'FSFAP', fullName: 'FSF All Permissive License', aliases: [] },
  {
    spdxId: 'FSFAP-no-warranty-disclaimer',
    fullName: 'FSF All Permissive License (without Warranty)',
    aliases: [],
  },
  {
    spdxId: 'FSFULLR',
    fullName: 'FSF Unlimited License (with License Retention)',
    aliases: [],
  },
  {
    spdxId: 'FSFULLRSD',
    fullName:
      'FSF Unlimited License (with License Retention and Short Disclaimer)',
    aliases: [],
  },
  {
    spdxId: 'FSFULLRWD',
    fullName:
      'FSF Unlimited License (With License Retention and Warranty Disclaimer)',
    aliases: [],
  },
  {
    spdxId: 'FTL',
    fullName: 'Freetype Project License',
    aliases: ['FreeType'],
  },
  { spdxId: 'Fair', fullName: 'Fair License', aliases: [] },
  {
    spdxId: 'Ferguson-Twofish',
    fullName: 'Ferguson Twofish License',
    aliases: [],
  },
  {
    spdxId: 'FreeBSD-DOC',
    fullName: 'FreeBSD Documentation License',
    aliases: [],
  },
  { spdxId: 'Furuseth', fullName: 'Furuseth License', aliases: [] },
  { spdxId: 'GD', fullName: 'GD License', aliases: [] },
  { spdxId: 'Graphics-Gems', fullName: 'Graphics Gems License', aliases: [] },
  { spdxId: 'Gutmann', fullName: 'Gutmann License', aliases: [] },
  { spdxId: 'HDF5', fullName: 'HDF5 License', aliases: [] },
  { spdxId: 'HIDAPI', fullName: 'HIDAPI License', aliases: [] },
  { spdxId: 'HP-1986', fullName: 'Hewlett-Packard 1986 License', aliases: [] },
  { spdxId: 'HP-1989', fullName: 'Hewlett-Packard 1989 License', aliases: [] },
  {
    spdxId: 'HPND',
    fullName: 'Historical Permission Notice and Disclaimer',
    aliases: [],
  },
  {
    spdxId: 'HPND-DEC',
    fullName: 'Historical Permission Notice and Disclaimer - DEC variant',
    aliases: [],
  },
  {
    spdxId: 'HPND-Fenneberg-Livingston',
    fullName:
      'Historical Permission Notice and Disclaimer - Fenneberg-Livingston variant',
    aliases: [],
  },
  {
    spdxId: 'HPND-INRIA-IMAG',
    fullName:
      'Historical Permission Notice and Disclaimer - INRIA-IMAG variant',
    aliases: [],
  },
  {
    spdxId: 'HPND-Intel',
    fullName: 'Historical Permission Notice and Disclaimer - Intel variant',
    aliases: [],
  },
  {
    spdxId: 'HPND-Kevlin-Henney',
    fullName:
      'Historical Permission Notice and Disclaimer - Kevlin Henney variant',
    aliases: [],
  },
  {
    spdxId: 'HPND-MIT-disclaimer',
    fullName: 'Historical Permission Notice and Disclaimer with MIT disclaimer',
    aliases: [],
  },
  {
    spdxId: 'HPND-Markus-Kuhn',
    fullName:
      'Historical Permission Notice and Disclaimer - Markus Kuhn variant',
    aliases: [],
  },
  {
    spdxId: 'HPND-Netrek',
    fullName: 'Historical Permission Notice and Disclaimer - Netrek variant',
    aliases: [],
  },
  {
    spdxId: 'HPND-Pbmplus',
    fullName: 'Historical Permission Notice and Disclaimer - Pbmplus variant',
    aliases: [],
  },
  {
    spdxId: 'HPND-UC',
    fullName:
      'Historical Permission Notice and Disclaimer - University of California variant',
    aliases: [],
  },
  {
    spdxId: 'HPND-doc',
    fullName:
      'Historical Permission Notice and Disclaimer - documentation variant',
    aliases: [],
  },
  {
    spdxId: 'HPND-doc-sell',
    fullName:
      'Historical Permission Notice and Disclaimer - documentation sell variant',
    aliases: [],
  },
  {
    spdxId: 'HPND-merchantability-variant',
    fullName:
      'Historical Permission Notice and Disclaimer - merchantability variant',
    aliases: [],
  },
  {
    spdxId: 'HPND-sell-MIT-disclaimer-xserver',
    fullName:
      'Historical Permission Notice and Disclaimer - sell xserver variant with MIT disclaimer',
    aliases: [],
  },
  {
    spdxId: 'HPND-sell-regexpr',
    fullName:
      'Historical Permission Notice and Disclaimer - sell regexpr variant',
    aliases: [],
  },
  {
    spdxId: 'HPND-sell-variant',
    fullName: 'Historical Permission Notice and Disclaimer - sell variant',
    aliases: [],
  },
  {
    spdxId: 'HPND-sell-variant-MIT-disclaimer',
    fullName: 'HPND sell variant with MIT disclaimer',
    aliases: [],
  },
  {
    spdxId: 'HPND-sell-variant-MIT-disclaimer-rev',
    fullName: 'HPND sell variant with MIT disclaimer - reverse',
    aliases: [],
  },
  {
    spdxId: 'HTMLTIDY',
    fullName: 'HTML Tidy License',
    aliases: ['JavaHTML/JTidy', 'Java HTML - JTidy License'],
  },
  { spdxId: 'ICU', fullName: 'ICU License', aliases: ['Unicode/ICU License'] },
  {
    spdxId: 'IJG',
    fullName: 'Independent JPEG Group License',
    aliases: ['JPEG License'],
  },
  {
    spdxId: 'IJG-short',
    fullName: 'Independent JPEG Group License - short',
    aliases: [],
  },
  {
    spdxId: 'ISC',
    fullName: 'ISC License',
    aliases: ['ISC', 'ISC License (ISCL)'],
  },
  { spdxId: 'ISC-Veillard', fullName: 'ISC Veillard variant', aliases: [] },
  {
    spdxId: 'ImageMagick',
    fullName: 'ImageMagick License',
    aliases: ['ImageMagick'],
  },
  { spdxId: 'Inner-Net-2.0', fullName: 'Inner Net License v2.0', aliases: [] },
  {
    spdxId: 'JPNIC',
    fullName: 'Japan Network Information Center License',
    aliases: [],
  },
  {
    spdxId: 'JSON',
    fullName: 'JSON License',
    aliases: ['JSON', 'The JSON License'],
  },
  { spdxId: 'Jam', fullName: 'Jam License', aliases: [] },
  { spdxId: 'Kastrup', fullName: 'Kastrup License', aliases: [] },
  { spdxId: 'Knuth-CTAN', fullName: 'Knuth CTAN License', aliases: [] },
  { spdxId: 'LOOP', fullName: 'Common Lisp LOOP License', aliases: [] },
  {
    spdxId: 'LZMA-SDK-9.11-to-9.20',
    fullName: 'LZMA SDK License (versions 9.11 to 9.20)',
    aliases: [],
  },
  {
    spdxId: 'LZMA-SDK-9.22',
    fullName: 'LZMA SDK License (versions 9.22 and beyond)',
    aliases: [],
  },
  { spdxId: 'Leptonica', fullName: 'Leptonica License', aliases: [] },
  { spdxId: 'Libpng', fullName: 'libpng License', aliases: [] },
  {
    spdxId: 'LicenseRef-NoVersion-Apache',
    fullName: 'Apache Software License',
    aliases: [
      'Apache',
      'Apache License',
      'OSI Approved :: Apache Software License',
    ],
  },
  {
    spdxId: 'LicenseRef-NoVersion-BSD',
    fullName: 'BSD License',
    aliases: ['BSD', 'The BSD License', 'BSD licence'],
  },
  {
    spdxId: 'LicenseRef-Proprietary-NVIDIA-CUDA-Python-2021',
    fullName: 'NVIDIA Software License for CUDA Python (2021)',
    aliases: [],
  },
  {
    spdxId: 'LicenseRef-Proprietary-NVIDIA-Math-Libraries-SDK-2022',
    fullName: 'License Agreement for NVIDIA Math Libraries SDKs (2022)',
    aliases: [],
  },
  {
    spdxId: 'LicenseRef-Proprietary-NVIDIA-Nsight-Systems-2024',
    fullName: 'Software License Agreement for NVIDIA Nsight Systems (2024)',
    aliases: [],
  },
  {
    spdxId: 'LicenseRef-Proprietary-NVIDIA-SDK-nvTIFF-2022',
    fullName: 'License Agreement for NVIDIA SDKs with nvTIFF Supplement (2022)',
    aliases: [],
  },
  {
    spdxId: 'LicenseRef-Proprietary-NVIDIA-TensorRT-2021',
    fullName: 'Software License Agreement for NVIDIA TensorRT (2021)',
    aliases: [],
  },
  {
    spdxId: 'LicenseRef-Proprietary-NVIDIA-Warp',
    fullName: 'Software License Agreement for NVIDIA Warp',
    aliases: [],
  },
  {
    spdxId: 'LicenseRef-com.oracle-BCL',
    fullName: 'Oracle Binary Code License',
    aliases: ['Sun Microsystems Binary Code'],
  },
  {
    spdxId: 'LicenseRef-scancode-amazon-sl',
    fullName: 'Amazon Software License',
    aliases: ['LicenseRef-.amazon.com.-AmznSL-1.0'],
  },
  {
    spdxId: 'LicenseRef-scancode-apple-excl',
    fullName: 'Apple Java Extensions',
    aliases: [],
  },
  {
    spdxId: 'LicenseRef-scancode-indiana-extreme',
    fullName: 'Indiana University Extreme! Lab Software 1.1.1',
    aliases: ['Indiana University Extreme! Lab Software License, vesion 1.1.1'],
  },
  {
    spdxId: 'LicenseRef-scancode-wordnet',
    fullName: 'WordNet 3.0 license',
    aliases: [],
  },
  {
    spdxId: 'Linux-OpenIB',
    fullName: 'Linux Kernel Variant of OpenIB.org license',
    aliases: [],
  },
  {
    spdxId: 'Linux-man-pages-1-para',
    fullName: 'Linux man-pages - 1 paragraph',
    aliases: [],
  },
  { spdxId: 'MIPS', fullName: 'MIPS License', aliases: [] },
  {
    spdxId: 'MIT',
    fullName: 'MIT License',
    aliases: [
      'MIT',
      'MIT License',
      'MIT Licence',
      'The MIT License',
      'MIT (LICENSE)',
      'MIT(LICENSE)',
      'The MIT License (MIT)',
      'Expat License',
      'The Expat License',
      'Bouncy Castle Licence',
      'MIT/X11',
      'MIT X11 License',
      '(MIT)',
      'The MIT License: http://www.opensource.org/licenses/mit-license.php',
      'MIT license',
      'MIT-License',
      'License :: OSI Approved :: MIT License',
      'MIT (https://opensource.org/licenses/MIT)',
      'SLF4J',
      'Expat',
    ],
  },
  {
    spdxId: 'MIT-0',
    fullName: 'MIT No Attribution License',
    aliases: ['MIT No Attribution', 'MIT-0 License'],
  },
  { spdxId: 'MIT-CMU', fullName: 'CMU License', aliases: [] },
  { spdxId: 'MIT-Click', fullName: 'MIT Click License', aliases: [] },
  { spdxId: 'MIT-Festival', fullName: 'MIT Festival Variant', aliases: [] },
  {
    spdxId: 'MIT-Khronos-old',
    fullName: 'MIT Khronos - old variant',
    aliases: [],
  },
  {
    spdxId: 'MIT-Modern-Variant',
    fullName: 'MIT License Modern Variant',
    aliases: [],
  },
  { spdxId: 'MIT-Wu', fullName: 'MIT Tom Wu Variant', aliases: [] },
  { spdxId: 'MIT-open-group', fullName: 'MIT Open Group variant', aliases: [] },
  { spdxId: 'MIT-testregex', fullName: 'MIT testregex Variant', aliases: [] },
  { spdxId: 'MITNFA', fullName: 'MIT +no-false-attribs license', aliases: [] },
  { spdxId: 'MMIXware', fullName: 'MMIXware License', aliases: [] },
  {
    spdxId: 'MPL-1.1',
    fullName: 'Mozilla Public License 1.1',
    aliases: ['MPLv1.1'],
  },
  {
    spdxId: 'MPL-2.0',
    fullName: 'Mozilla Public License 2.0',
    aliases: [
      'MPLv2',
      'MPLv2.0',
      'MPL 2.0',
      'MPL2.0',
      'Mozilla Public License 2.0 (MPL 2.0)',
      'Mozilla Public License v. 2.0',
      'Mozilla Public License, Version 2.0',
      'Mozilla Public License Version 2.0',
      'MPL v2.0',
      'MPL-2',
      'MPL2',
    ],
  },
  {
    spdxId: 'MPL-2.0-no-copyleft-exception',
    fullName: 'Mozilla Public License 2.0 (no copyleft exception)',
    aliases: [],
  },
  {
    spdxId: 'MS-PL',
    fullName: 'Microsoft Public License',
    aliases: ['Microsoft Public'],
  },
  {
    spdxId: 'Mackerras-3-Clause',
    fullName: 'Mackerras 3-Clause License',
    aliases: [],
  },
  {
    spdxId: 'Mackerras-3-Clause-acknowledgment',
    fullName: 'Mackerras 3-Clause - acknowledgment variant',
    aliases: [],
  },
  {
    spdxId: 'Martin-Birgmeier',
    fullName: 'Martin Birgmeier License',
    aliases: [],
  },
  { spdxId: 'Minpack', fullName: 'Minpack License', aliases: [] },
  { spdxId: 'MirOS', fullName: 'MirOS Licence', aliases: [] },
  {
    spdxId: 'MulanPSL-2.0',
    fullName: 'Mulan Permissive Software License, Version 2',
    aliases: ['MulanPSL2'],
  },
  { spdxId: 'NCBI-PD', fullName: 'NCBI Public Domain Notice', aliases: [] },
  { spdxId: 'NCL', fullName: 'NCL Source Code License', aliases: [] },
  {
    spdxId: 'NCSA',
    fullName: 'University of Illinois/NCSA Open Source License',
    aliases: [
      'University of Illinois/NCSA',
      'The University of Illinois/NCSA Open Source License (NCSA)',
    ],
  },
  {
    spdxId: 'NICTA-1.0',
    fullName: 'NICTA Public Software License, Version 1.0',
    aliases: [],
  },
  { spdxId: 'NIST-PD', fullName: 'NIST Public Domain Notice', aliases: [] },
  { spdxId: 'NIST-Software', fullName: 'NIST Software License', aliases: [] },
  { spdxId: 'NLPL', fullName: 'No Limit Public License', aliases: [] },
  { spdxId: 'NTIA-PD', fullName: 'NTIA Public Domain Notice', aliases: [] },
  { spdxId: 'NTP', fullName: 'NTP License', aliases: [] },
  { spdxId: 'NTP-0', fullName: 'NTP No Attribution', aliases: [] },
  { spdxId: 'Net-SNMP', fullName: 'Net-SNMP License', aliases: [] },
  { spdxId: 'OAR', fullName: 'OAR License', aliases: [] },
  { spdxId: 'OFFIS', fullName: 'OFFIS License', aliases: [] },
  {
    spdxId: 'OFL-1.0',
    fullName: 'SIL Open Font License 1.0',
    aliases: ['SIL OPEN FONT LICENSE', 'Font Awesome Free'],
  },
  {
    spdxId: 'OFL-1.0-RFN',
    fullName: 'SIL Open Font License 1.0 with Reserved Font Name',
    aliases: [],
  },
  {
    spdxId: 'OFL-1.0-no-RFN',
    fullName: 'SIL Open Font License 1.0 with no Reserved Font Name',
    aliases: [],
  },
  { spdxId: 'OFL-1.1', fullName: 'SIL Open Font License 1.1', aliases: [] },
  {
    spdxId: 'OFL-1.1-RFN',
    fullName: 'SIL Open Font License 1.1 with Reserved Font Name',
    aliases: [],
  },
  {
    spdxId: 'OFL-1.1-no-RFN',
    fullName: 'SIL Open Font License 1.1 with no Reserved Font Name',
    aliases: [],
  },
  {
    spdxId: 'OGC-1.0',
    fullName: 'OGC Software License, Version 1.0',
    aliases: [],
  },
  {
    spdxId: 'OLDAP-2.0',
    fullName: 'Open LDAP Public License v2.0 (or possibly 2.0A and 2.0B)',
    aliases: [],
  },
  {
    spdxId: 'OLDAP-2.0.1',
    fullName: 'Open LDAP Public License v2.0.1',
    aliases: [],
  },
  {
    spdxId: 'OLDAP-2.1',
    fullName: 'Open LDAP Public License v2.1',
    aliases: [],
  },
  {
    spdxId: 'OLDAP-2.2',
    fullName: 'Open LDAP Public License v2.2',
    aliases: [],
  },
  {
    spdxId: 'OLDAP-2.2.1',
    fullName: 'Open LDAP Public License v2.2.1',
    aliases: [],
  },
  {
    spdxId: 'OLDAP-2.2.2',
    fullName: 'Open LDAP Public License 2.2.2',
    aliases: [],
  },
  {
    spdxId: 'OLDAP-2.3',
    fullName: 'Open LDAP Public License v2.3',
    aliases: [],
  },
  {
    spdxId: 'OLDAP-2.4',
    fullName: 'Open LDAP Public License v2.4',
    aliases: [],
  },
  {
    spdxId: 'OLDAP-2.5',
    fullName: 'Open LDAP Public License v2.5',
    aliases: [],
  },
  {
    spdxId: 'OLDAP-2.6',
    fullName: 'Open LDAP Public License v2.6',
    aliases: [],
  },
  {
    spdxId: 'OLDAP-2.7',
    fullName: 'Open LDAP Public License v2.7',
    aliases: [],
  },
  {
    spdxId: 'OLDAP-2.8',
    fullName: 'Open LDAP Public License v2.8',
    aliases: ['OpenLDAP'],
  },
  { spdxId: 'OpenSSL', fullName: 'OpenSSL License', aliases: ['OpenSSL'] },
  {
    spdxId: 'OpenSSL-standalone',
    fullName: 'OpenSSL License - standalone',
    aliases: [],
  },
  { spdxId: 'PADL', fullName: 'PADL License', aliases: [] },
  {
    spdxId: 'PDDL-1.0',
    fullName: 'ODC Public Domain Dedication & License 1.0',
    aliases: ['PDDL (Public Domain Dedication and License)'],
  },
  { spdxId: 'PHP-3.0', fullName: 'PHP License v3.0', aliases: ['PHP'] },
  { spdxId: 'PHP-3.01', fullName: 'PHP LIcense v3.01', aliases: [] },
  {
    spdxId: 'PSF-2.0',
    fullName: 'Python Software Foundation License 2.0',
    aliases: [
      'PSF',
      'Python Software Foundation License',
      'PSF License',
      'PSFL',
      'PSFL 2',
      'PSF 2.0',
      'Python Software Foundation License v 2.1.1',
      'Python v2.1.1',
      'Python Software Foundation License Version 2',
    ],
  },
  { spdxId: 'Pixar', fullName: 'Pixar License', aliases: [] },
  {
    spdxId: 'PostgreSQL',
    fullName: 'PostgreSQL License',
    aliases: ['PostgreSQL'],
  },
  { spdxId: 'Python-2.0', fullName: 'Python License 2.0', aliases: [] },
  { spdxId: 'Python-2.0.1', fullName: 'Python License 2.0.1', aliases: [] },
  { spdxId: 'Ruby', fullName: 'Ruby License', aliases: ['Ruby'] },
  { spdxId: 'Ruby-pty', fullName: 'Ruby pty extension license', aliases: [] },
  {
    spdxId: 'SAX-PD-2.0',
    fullName: 'Sax Public Domain Notice 2.0',
    aliases: [],
  },
  {
    spdxId: 'SGI-B-2.0',
    fullName: 'SGI Free Software License B v2.0',
    aliases: [],
  },
  { spdxId: 'SL', fullName: 'SL License', aliases: [] },
  {
    spdxId: 'SMLNJ',
    fullName: 'Standard ML of New Jersey License',
    aliases: [
      'Standard ML of New Jersey License',
      'CUP Parser Generator Copyright Notice, License, and Disclaimer',
    ],
  },
  {
    spdxId: 'SMPPL',
    fullName: 'Secure Messaging Protocol Public License',
    aliases: [],
  },
  { spdxId: 'SSH-OpenSSH', fullName: 'SSH OpenSSH license', aliases: [] },
  { spdxId: 'SSH-short', fullName: 'SSH short notice', aliases: [] },
  {
    spdxId: 'SSLeay-standalone',
    fullName: 'SSLeay License - standalone',
    aliases: [],
  },
  { spdxId: 'Soundex', fullName: 'Soundex License', aliases: [] },
  { spdxId: 'Spencer-86', fullName: 'Spencer License 86', aliases: [] },
  { spdxId: 'Spencer-94', fullName: 'Spencer License 94', aliases: [] },
  { spdxId: 'Spencer-99', fullName: 'Spencer License 99', aliases: [] },
  {
    spdxId: 'StandardML-NJ',
    fullName: 'Standard ML of New Jersey License',
    aliases: ['Standard ML of New Jersey License'],
  },
  { spdxId: 'Sun-PPP', fullName: 'Sun PPP License', aliases: [] },
  { spdxId: 'Sun-PPP-2000', fullName: 'Sun PPP License (2000)', aliases: [] },
  { spdxId: 'SunPro', fullName: 'SunPro License', aliases: [] },
  { spdxId: 'Symlinks', fullName: 'Symlinks License', aliases: [] },
  { spdxId: 'TCL', fullName: 'Tcl/Tk', aliases: [] },
  { spdxId: 'TCP-wrappers', fullName: 'TCP Wrappers License', aliases: [] },
  { spdxId: 'TPDL', fullName: 'Time::ParseDate License', aliases: [] },
  { spdxId: 'TPL-1.0', fullName: 'THOR Public License 1.0', aliases: [] },
  { spdxId: 'TTWL', fullName: 'Text-Tabs+Wrap License', aliases: [] },
  { spdxId: 'TTYP0', fullName: 'TTYP0 License', aliases: [] },
  {
    spdxId: 'TU-Berlin-1.0',
    fullName: 'Technische Universitaet Berlin License 1.0',
    aliases: [],
  },
  {
    spdxId: 'TU-Berlin-2.0',
    fullName: 'Technische Universitaet Berlin License 2.0',
    aliases: [],
  },
  { spdxId: 'TermReadKey', fullName: 'TermReadKey License', aliases: [] },
  { spdxId: 'ThirdEye', fullName: 'ThirdEye License', aliases: [] },
  { spdxId: 'TrustedQSL', fullName: 'TrustedQSL License', aliases: [] },
  { spdxId: 'UCAR', fullName: 'UCAR License', aliases: [] },
  {
    spdxId: 'UMich-Merit',
    fullName: 'Michigan/Merit Networks License',
    aliases: [],
  },
  {
    spdxId: 'UPL-1.0',
    fullName: 'Universal Permissive License v1.0',
    aliases: [
      'Universal Permissive License, Version 1.0',
      'Universal Permissive License v 1.0',
      'Universal Permissive License Version 1.0',
      'Universal Permissive License (UPL)',
    ],
  },
  {
    spdxId: 'Ubuntu-font-1.0',
    fullName: 'Ubuntu Font Licence v1.0',
    aliases: [],
  },
  { spdxId: 'Unicode-3.0', fullName: 'Unicode License v3', aliases: [] },
  {
    spdxId: 'Unicode-DFS-2015',
    fullName: 'Unicode License Agreement - Data Files and Software (2015)',
    aliases: [],
  },
  {
    spdxId: 'Unicode-DFS-2016',
    fullName: 'Unicode License Agreement - Data Files and Software (2016)',
    aliases: [],
  },
  { spdxId: 'UnixCrypt', fullName: 'UnixCrypt License', aliases: [] },
  {
    spdxId: 'Unlicense',
    fullName: 'Unlicense',
    aliases: ['unlicense.org', 'The Unlicense', 'The Unlicense (Unlicense)'],
  },
  {
    spdxId: 'Unlicense-libtelnet',
    fullName: 'Unlicense - libtelnet variant',
    aliases: [],
  },
  {
    spdxId: 'Unlicense-libwhirlpool',
    fullName: 'Unlicense - libwhirlpool variant',
    aliases: [],
  },
  { spdxId: 'Vim', fullName: 'Vim License', aliases: [] },
  {
    spdxId: 'W3C',
    fullName: 'W3C Software and Notice License',
    aliases: ['W3C'],
  },
  {
    spdxId: 'W3C-19980720',
    fullName: 'W3C Software Notice and License (1998-07-20)',
    aliases: [],
  },
  {
    spdxId: 'W3C-20150513',
    fullName: 'W3C Software Notice and Document License (2015-05-13)',
    aliases: [],
  },
  {
    spdxId: 'WTFPL',
    fullName: 'Do What The F*ck You Want To Public License',
    aliases: ['WTFPL2'],
  },
  {
    spdxId: 'Widget-Workshop',
    fullName: 'Widget Workshop License',
    aliases: [],
  },
  { spdxId: 'X11', fullName: 'X11 License', aliases: [] },
  {
    spdxId: 'X11-distribute-modifications-variant',
    fullName: 'X11 License Distribution Modification Variant',
    aliases: [],
  },
  {
    spdxId: 'X11-swapped',
    fullName: 'X11 swapped final paragraphs',
    aliases: [],
  },
  { spdxId: 'XFree86-1.1', fullName: 'XFree86 License 1.1', aliases: [] },
  { spdxId: 'Xdebug-1.03', fullName: 'Xdebug License v 1.03', aliases: [] },
  { spdxId: 'Xfig', fullName: 'Xfig License', aliases: [] },
  { spdxId: 'Xnet', fullName: 'X.Net License', aliases: [] },
  {
    spdxId: 'ZPL-2.1',
    fullName: 'Zope Public License 2.1',
    aliases: ['Zope Public 2.1', 'ZPL 2.1', 'ZPLv2.1'],
  },
  { spdxId: 'Zed', fullName: 'Zed License', aliases: [] },
  { spdxId: 'Zeeff', fullName: 'Zeeff License', aliases: [] },
  {
    spdxId: 'Zlib',
    fullName: 'zlib License',
    aliases: [
      'Zlib/libpng',
      'zlib',
      'The zlib/libpng License',
      'The zlib/libpng License (Zlib)',
      'Zlib/PNG License',
    ],
  },
  {
    spdxId: 'any-OSI-perl-modules',
    fullName: 'Any OSI License - Perl Modules',
    aliases: [],
  },
  {
    spdxId: 'bcrypt-Solar-Designer',
    fullName: 'bcrypt Solar Designer License',
    aliases: [],
  },
  { spdxId: 'blessing', fullName: 'SQLite Blessing', aliases: [] },
  {
    spdxId: 'bzip2-1.0.6',
    fullName: 'bzip2 and libbzip2 License v1.0.6',
    aliases: [],
  },
  { spdxId: 'check-cvs', fullName: 'check-cvs License', aliases: [] },
  { spdxId: 'checkmk', fullName: 'Checkmk License', aliases: [] },
  { spdxId: 'curl', fullName: 'curl License', aliases: [] },
  {
    spdxId: 'cve-tou',
    fullName: 'Common Vulnerability Enumeration ToU License',
    aliases: [],
  },
  { spdxId: 'dtoa', fullName: 'David M. Gay dtoa License', aliases: [] },
  { spdxId: 'fwlw', fullName: 'fwlw License', aliases: [] },
  { spdxId: 'generic-xts', fullName: 'Generic XTS License', aliases: [] },
  { spdxId: 'gtkbook', fullName: 'gtkbook License', aliases: [] },
  { spdxId: 'hdparm', fullName: 'hdparm License', aliases: [] },
  { spdxId: 'jove', fullName: 'Jove License', aliases: [] },
  {
    spdxId: 'libpng-1.6.35',
    fullName:
      'PNG Reference Library License v1 (for libpng 0.5 through 1.6.35)',
    aliases: [],
  },
  {
    spdxId: 'libpng-2.0',
    fullName: 'PNG Reference Library version 2',
    aliases: [],
  },
  {
    spdxId: 'libselinux-1.0',
    fullName: 'libselinux public domain notice',
    aliases: [],
  },
  { spdxId: 'libtiff', fullName: 'libtiff License', aliases: [] },
  {
    spdxId: 'libutil-David-Nugent',
    fullName: 'libutil David Nugent License',
    aliases: [],
  },
  { spdxId: 'lsof', fullName: 'lsof License', aliases: [] },
  { spdxId: 'magaz', fullName: 'magaz License', aliases: [] },
  { spdxId: 'mailprio', fullName: 'mailprio License', aliases: [] },
  { spdxId: 'man2html', fullName: 'man2html License', aliases: [] },
  { spdxId: 'metamail', fullName: 'metamail License', aliases: [] },
  { spdxId: 'mpi-permissive', fullName: 'mpi Permissive License', aliases: [] },
  { spdxId: 'mplus', fullName: 'mplus Font License', aliases: [] },
  { spdxId: 'pkgconf', fullName: 'pkgconf License', aliases: [] },
  { spdxId: 'snprintf', fullName: 'snprintf License', aliases: [] },
  { spdxId: 'softSurfer', fullName: 'softSurfer License', aliases: [] },
  { spdxId: 'ssh-keyscan', fullName: 'ssh-keyscan License', aliases: [] },
  { spdxId: 'swrule', fullName: 'swrule License', aliases: [] },
  { spdxId: 'threeparttable', fullName: 'threeparttable License', aliases: [] },
  { spdxId: 'ulem', fullName: 'ulem License', aliases: [] },
  { spdxId: 'w3m', fullName: 'w3m License', aliases: [] },
  {
    spdxId: 'xkeyboard-config-Zinoviev',
    fullName: 'xkeyboard-config Zinoviev License',
    aliases: [],
  },
  { spdxId: 'xlock', fullName: 'xlock License', aliases: [] },
  { spdxId: 'xpp', fullName: 'XPP License', aliases: [] },
  {
    spdxId: 'zlib-acknowledgement',
    fullName: 'zlib/libpng License with Acknowledgement',
    aliases: [],
  },
];
