name: 🚀 Feature Request
description: Suggest a new feature.
labels: ['enhancement', 'needs-triage']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed description of the feature you would like to see.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you want this feature?
    validations:
      required: true
  - type: textarea
    id: suggested_implementation
    attributes:
      label: Suggested Implementation
      description: Please provide a detailed description of how you would implement this feature.
  - type: checkboxes
    id: implementation_appetite
    attributes:
      label: Contribute to feature
      options:
        - label: I'd be willing to implement this feature