name: 📖 Documentation issue
description: Suggest improvements to documentation
labels: ['documentation', 'needs-triage']
body:
  - type: dropdown
    id: issue_type
    attributes:
      label: Issue type
      description: What type of issue is this?
      options:
        - Typo
        - Bug
        - Question
        - Enhancement
      multiple: false
    validations:
      required: true
  - type: textarea
    id: specific_problem_page
    attributes:
      label: Is there a specific page(s) that this issue relates to?
      description: Please provide a link to the page(s) you want to see improved.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a description of the issue.
    validations:
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Please provide any additional context that may be helpful.