/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import {
  joinPathFragments,
  type ProjectConfiguration,
  type Tree,
} from '@nx/devkit';

/**
 * Directory within a Smithy project into which the sources of the shape
 * libraries it depends on are copied. Smithy models are resolved by the Smithy
 * CLI running inside a Docker build whose context is the project directory, so
 * dependencies must be materialised inside the project to be visible.
 */
export const SMITHY_DEPS_DIR = '.smithy-deps';

const DOCKERFILE_COPY = `COPY ${SMITHY_DEPS_DIR} ${SMITHY_DEPS_DIR}`;

/**
 * Path within a consuming project at which the given dependency's sources land
 */
export const smithyDepPath = (projectRoot: string, dependencyName: string) =>
  joinPathFragments(projectRoot, SMITHY_DEPS_DIR, dependencyName);

/**
 * Directory name used for a dependency within `.smithy-deps`. Dependencies are
 * keyed by name so that a shape library reached by more than one path is copied
 * to a single location rather than defining its shapes twice.
 */
export const smithyDepDirName = (projectName: string) =>
  projectName.slice(projectName.lastIndexOf('/') + 1);

/**
 * The full set of shape libraries a Smithy project's model depends on,
 * including those reached transitively.
 */
export const readSmithyDependencies = (
  projectConfig: ProjectConfiguration,
): string[] => ((projectConfig.metadata as any) ?? {}).smithyDependencies ?? [];

/**
 * Ensure a Smithy project is set up to consume shape libraries.
 *
 * Projects generated by `smithy#project` are already configured, so this only
 * has an effect on projects generated before shape library support existed.
 * Each step is guarded so re-running is a no-op.
 */
export const ensureSmithyDepsSupport = (tree: Tree, projectRoot: string) => {
  const gitKeepPath = joinPathFragments(
    projectRoot,
    SMITHY_DEPS_DIR,
    '.gitkeep',
  );
  if (!tree.exists(gitKeepPath)) {
    tree.write(gitKeepPath, '');
  }

  ensureDockerfileCopiesDeps(tree, projectRoot);
  ensureSmithyBuildIncludesDeps(tree, projectRoot);
};

/**
 * Add the `.smithy-deps` COPY to the project's Dockerfile, immediately after
 * the sources are copied in, so dependencies are present when `smithy build`
 * runs.
 */
const ensureDockerfileCopiesDeps = (tree: Tree, projectRoot: string) => {
  const dockerfilePath = joinPathFragments(projectRoot, 'build.Dockerfile');
  const dockerfile = tree.read(dockerfilePath, 'utf-8');

  if (dockerfile === null || dockerfile.includes(DOCKERFILE_COPY)) {
    return;
  }

  const lines = dockerfile.split('\n');
  const copySrcIndex = lines.findIndex(
    (line) => line.trim() === 'COPY src src',
  );

  if (copySrcIndex === -1) {
    throw new Error(
      `Unable to add the ${SMITHY_DEPS_DIR} directory to ${dockerfilePath}, since it does not copy its Smithy sources with "COPY src src". ` +
        `Add "${DOCKERFILE_COPY}" after the sources are copied in to consume shape libraries.`,
    );
  }

  lines.splice(copySrcIndex + 1, 0, DOCKERFILE_COPY);
  tree.write(dockerfilePath, lines.join('\n'));
};

/**
 * Add `.smithy-deps/` to the sources in the project's smithy-build.json so the
 * shapes copied in are loaded as part of the model.
 */
const ensureSmithyBuildIncludesDeps = (tree: Tree, projectRoot: string) => {
  const smithyBuildPath = joinPathFragments(projectRoot, 'smithy-build.json');
  const contents = tree.read(smithyBuildPath, 'utf-8');

  if (contents === null) {
    throw new Error(`No smithy-build.json file found at ${smithyBuildPath}`);
  }

  let smithyBuild: { sources?: string[] };
  try {
    smithyBuild = JSON.parse(contents);
  } catch {
    throw new Error(`Unable to parse ${smithyBuildPath} as JSON`);
  }

  const sources = smithyBuild.sources ?? [];
  const depsSource = `${SMITHY_DEPS_DIR}/`;

  if (sources.includes(depsSource)) {
    return;
  }

  tree.write(
    smithyBuildPath,
    JSON.stringify(
      { ...smithyBuild, sources: [...sources, depsSource] },
      null,
      2,
    ),
  );
};
