/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import { OPEN_API_PY_CLIENT_DEPENDENCIES } from '../../open-api/py-client/generator.js';
import { declaredNames } from '../declared-dependencies.js';
import { PY_VERSIONS, withPyVersions } from '../versions.js';

/**
 * The packages a client generated by `open-api#py-client` imports, at the
 * versions the generator vends — so a worker runs the code under test against
 * exactly what a consumer gets.
 */
export const PY_CLIENT_VERIFIER_DEPENDENCIES: string[] = withPyVersions(
  OPEN_API_PY_CLIENT_DEPENDENCIES,
  declaredNames(OPEN_API_PY_CLIENT_DEPENDENCIES.py),
);

/** The type checker every Python worker installs alongside its dependencies. */
export const PY_VERIFIER_TYPE_CHECKER = `ty${PY_VERSIONS.ty}`;
