/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import type { MigrationReturnObject, Tree } from '@nx/devkit';
import {
  addDestructuredImport,
  applyGritQL,
  matchGritQL,
} from '../../../utils/ast.js';
import { formatFilesInSubtree } from '../../../utils/format.js';
import {
  PACKAGES_DIR,
  SHARED_CONSTRUCTS_DIR,
  SHARED_TERRAFORM_DIR,
} from '../../../utils/shared-constructs-constants.js';

/**
 * Surface mfa and mfaSecondFactor on the vended UserIdentity construct/module
 *
 * CDK's `mfa` / `mfaSecondFactor` props default to what the construct already
 * hard-coded (`Mfa.REQUIRED` / `{ sms: true, otp: true }`), so this just makes
 * them overridable, matching the existing `enableWaf` prop pattern.
 *
 * Terraform has no equivalent of CloudFormation's `EnabledMfas` - SMS MFA is
 * inseparable from the `sms_configuration` block, which phone number
 * verification also relies on. So `mfa_second_factor_sms` gates
 * `sms_configuration` (and, with it, SMS phone verification) rather than only
 * MFA, unlike the CDK prop.
 *
 * CDK has the same underlying coupling for any non-OFF `mfa`: Cognito rejects
 * `SmsConfiguration` (which CDK emits whenever phone is auto-verified) unless
 * SMS is also an enabled MFA method. So `phoneVerificationEnabled` gates
 * `autoVerify`/`keepOriginal`'s `phone` flag on whether SMS is actually usable
 * as a second factor, and a `mfa: REQUIRED` with neither `sms` nor `otp`
 * enabled - a pool nobody could ever sign into - is rejected at synth time.
 *
 * How to write a migration:
 * - https://nx.dev/docs/kb/migration-generators
 * - What `nextSteps` means: https://nx.dev/docs/reference/devkit/MigrationReturnObject
 *
 * Guardrails:
 * - Pattern-match before writing: skip files that have diverged from the shape
 *   your generators produce and report them via `nextSteps`, rather than
 *   clobbering the user's changes.
 * - Idempotent: re-running must be a no-op.
 * - Format what you write: finish with `formatFilesInSubtree` so the files your
 *   migration wrote are formatted correctly.
 */

const CDK_USER_IDENTITY_FILE = `${PACKAGES_DIR}/${SHARED_CONSTRUCTS_DIR}/src/core/user-identity.ts`;
const TERRAFORM_IDENTITY_FILE = `${PACKAGES_DIR}/${SHARED_TERRAFORM_DIR}/src/core/user-identity/identity/identity.tf`;
const TERRAFORM_MAIN_FILE = `${PACKAGES_DIR}/${SHARED_TERRAFORM_DIR}/src/core/user-identity/main.tf`;

const NEW_TERRAFORM_VARIABLES = `variable "mfa" {
  description = "Whether users must configure MFA, may optionally configure MFA, or cannot use MFA at all"
  type        = string
  default     = "ON"

  validation {
    condition     = contains(["OFF", "OPTIONAL", "ON"], var.mfa)
    error_message = "mfa must be one of OFF, OPTIONAL, ON"
  }
}

variable "mfa_second_factor_otp" {
  description = "Whether users can use a time-based one time password (TOTP), generated by a hardware or software token, as an MFA method"
  type        = bool
  default     = true
}

variable "mfa_second_factor_sms" {
  description = "Whether users can use SMS to their verified phone numbers as an MFA method. Due to a Terraform AWS provider limitation, disabling this also disables SMS-based phone number verification, unlike the equivalent CDK construct prop"
  type        = bool
  default     = true
}`;

// Guards each file: present only once it has been migrated.
const CDK_MIGRATED_PATTERN = '`mfa === Mfa.OFF || mfaSecondFactor.sms`';
const TERRAFORM_IDENTITY_MIGRATED_PATTERN =
  'language hcl\n`mfa_configuration = var.mfa`';
const TERRAFORM_MAIN_MIGRATED_PATTERN = 'language hcl\n`mfa = var.mfa`';

// Interface members don't parse as standalone snippets, so this anchors on the
// whole interface body (preserved via $body) rather than the enableWaf member.
const CDK_INTERFACE_BODY_PATTERN =
  '`export interface UserIdentityProps { $body }`';
// A parameter's type annotation blocks matching the destructure sub-pattern in
// isolation, so this anchors on the full constructor signature instead
// (literal params so a customised signature is correctly seen as diverged).
const CDK_CONSTRUCTOR_PATTERN =
  '`constructor(scope: Construct, id: string, { enableWaf = true }: UserIdentityProps = {}) { $body }`';
const CDK_CREATE_CALL_PATTERN = '`this.createUserPool()`';
const CDK_CREATE_SIGNATURE_PATTERN = '`private createUserPool = () => $body`';
// Trailing commas block matching a bare object property in isolation; the
// separator is outside the matched span either way, so it survives untouched.
const CDK_MFA_FIELD_PATTERN = '`mfa: Mfa.REQUIRED`';
const CDK_MFA_SECOND_FACTOR_FIELD_PATTERN =
  '`mfaSecondFactor: { sms: true, otp: true }`';
const CDK_SUPER_CALL_PATTERN = '`super(scope, id);`';
// $props preserves the whole (large) UserPool props object untouched while
// inserting the new const declaration immediately before it.
const CDK_NEW_USER_POOL_PATTERN =
  "`const userPool = new UserPool(this, 'UserPool', { $props })`";
// Matches both the autoVerify.phone and keepOriginal.phone occurrences in one pass.
const CDK_PHONE_TRUE_PATTERN = '`phone: true`';

const CDK_EDITS: Array<[string, string]> = [
  [
    CDK_INTERFACE_BODY_PATTERN,
    `${CDK_INTERFACE_BODY_PATTERN} => \`export interface UserIdentityProps {
  $body

  /**
   * Whether users must configure MFA, may optionally configure MFA, or cannot use MFA at all.
   *
   * @default Mfa.REQUIRED
   */
  readonly mfa?: Mfa;

  /**
   * The MFA methods available to users when MFA is not off.
   *
   * @default { sms: true, otp: true }
   */
  readonly mfaSecondFactor?: MfaSecondFactor;
}\``,
  ],
  [
    CDK_CONSTRUCTOR_PATTERN,
    `${CDK_CONSTRUCTOR_PATTERN} => \`constructor(
    scope: Construct,
    id: string,
    {
      enableWaf = true,
      mfa = Mfa.REQUIRED,
      mfaSecondFactor = { sms: true, otp: true },
    }: UserIdentityProps = {},
  ) { $body }\``,
  ],
  [
    CDK_CREATE_CALL_PATTERN,
    `${CDK_CREATE_CALL_PATTERN} => \`this.createUserPool(mfa, mfaSecondFactor)\``,
  ],
  [
    CDK_CREATE_SIGNATURE_PATTERN,
    `${CDK_CREATE_SIGNATURE_PATTERN} => \`private createUserPool = (mfa: Mfa, mfaSecondFactor: MfaSecondFactor) => $body\``,
  ],
  [CDK_MFA_FIELD_PATTERN, `${CDK_MFA_FIELD_PATTERN} => \`mfa\``],
  [
    CDK_MFA_SECOND_FACTOR_FIELD_PATTERN,
    `${CDK_MFA_SECOND_FACTOR_FIELD_PATTERN} => \`mfaSecondFactor\``,
  ],
  [
    CDK_SUPER_CALL_PATTERN,
    `${CDK_SUPER_CALL_PATTERN} => \`super(scope, id);

    if (mfa === Mfa.REQUIRED && !mfaSecondFactor.sms && !mfaSecondFactor.otp) {
      throw new Error(
        'UserIdentity: mfa is REQUIRED but mfaSecondFactor has no methods enabled (sms and otp are both false)',
      );
    }\``,
  ],
  [
    CDK_NEW_USER_POOL_PATTERN,
    `${CDK_NEW_USER_POOL_PATTERN} => \`const phoneVerificationEnabled = mfa === Mfa.OFF || mfaSecondFactor.sms;

    const userPool = new UserPool(this, 'UserPool', { $props })\``,
  ],
  [
    CDK_PHONE_TRUE_PATTERN,
    `${CDK_PHONE_TRUE_PATTERN} => \`phone: phoneVerificationEnabled\``,
  ],
];

const TERRAFORM_IDENTITY_ENABLE_WAF_VARIABLE_ANCHOR = [
  'language hcl',
  '`variable "enable_waf" {',
  '  description = "Whether to enable AWS WAFv2 with the default managed ruleset (AWSManagedRulesCommonRuleSet and AWSManagedRulesKnownBadInputsRuleSet) and associate it with the user pool"',
  '  type        = bool',
  '  default     = true',
  '}`',
].join('\n');

const TERRAFORM_MFA_CONFIGURATION_PATTERN = [
  'language hcl',
  '`mfa_configuration = "ON"`',
].join('\n');

const TERRAFORM_SOFTWARE_TOKEN_MFA_PATTERN = [
  'language hcl',
  '`software_token_mfa_configuration {',
  '    enabled = true',
  '  }`',
].join('\n');

const TERRAFORM_SMS_CONFIGURATION_PATTERN = [
  'language hcl',
  '`sms_configuration {',
  '    external_id    = random_uuid.sms_external_id.result',
  '    sns_caller_arn = aws_iam_role.cognito_sms_role.arn',
  '    sns_region     = data.aws_region.current.region',
  '  }`',
].join('\n');

const TERRAFORM_RANDOM_UUID_PATTERN = [
  'language hcl',
  '`resource "random_uuid" "sms_external_id" {}`',
].join('\n');

const TERRAFORM_SMS_ROLE_PATTERN = [
  'language hcl',
  '`resource "aws_iam_role" "cognito_sms_role" { $body }`',
].join('\n');

const TERRAFORM_SMS_POLICY_PATTERN = [
  'language hcl',
  '`resource "aws_iam_role_policy" "cognito_sms_policy" { $body }`',
].join('\n');

const TERRAFORM_SMS_ROLE_ID_REF_PATTERN = [
  'language hcl',
  '`aws_iam_role.cognito_sms_role.id`',
].join('\n');

const TERRAFORM_EXTERNAL_ID_REF_PATTERN = [
  'language hcl',
  '`random_uuid.sms_external_id.result`',
].join('\n');

const TERRAFORM_AUTO_VERIFIED_ATTRIBUTES_PATTERN = [
  'language hcl',
  '`auto_verified_attributes = ["email", "phone_number"]`',
].join('\n');

const TERRAFORM_ATTRIBUTES_REQUIRE_VERIFICATION_PATTERN = [
  'language hcl',
  '`attributes_require_verification_before_update = ["email", "phone_number"]`',
].join('\n');

const TERRAFORM_IDENTITY_EDITS: Array<[string, string]> = [
  [
    TERRAFORM_IDENTITY_ENABLE_WAF_VARIABLE_ANCHOR,
    `${TERRAFORM_IDENTITY_ENABLE_WAF_VARIABLE_ANCHOR} => \`variable "enable_waf" {
  description = "Whether to enable AWS WAFv2 with the default managed ruleset (AWSManagedRulesCommonRuleSet and AWSManagedRulesKnownBadInputsRuleSet) and associate it with the user pool"
  type        = bool
  default     = true
}

${NEW_TERRAFORM_VARIABLES}\``,
  ],
  [
    TERRAFORM_RANDOM_UUID_PATTERN,
    `${TERRAFORM_RANDOM_UUID_PATTERN} => \`resource "random_uuid" "sms_external_id" {
  count = var.mfa_second_factor_sms ? 1 : 0
}\``,
  ],
  [
    TERRAFORM_SMS_ROLE_PATTERN,
    `${TERRAFORM_SMS_ROLE_PATTERN} => \`resource "aws_iam_role" "cognito_sms_role" {
  count = var.mfa_second_factor_sms ? 1 : 0

  $body
}\``,
  ],
  [
    TERRAFORM_SMS_POLICY_PATTERN,
    `${TERRAFORM_SMS_POLICY_PATTERN} => \`resource "aws_iam_role_policy" "cognito_sms_policy" {
  count = var.mfa_second_factor_sms ? 1 : 0

  $body
}\``,
  ],
  [
    TERRAFORM_MFA_CONFIGURATION_PATTERN,
    `${TERRAFORM_MFA_CONFIGURATION_PATTERN} => \`mfa_configuration = var.mfa\``,
  ],
  [
    TERRAFORM_SOFTWARE_TOKEN_MFA_PATTERN,
    `${TERRAFORM_SOFTWARE_TOKEN_MFA_PATTERN} => \`software_token_mfa_configuration {
    enabled = var.mfa_second_factor_otp
  }\``,
  ],
  [
    TERRAFORM_SMS_CONFIGURATION_PATTERN,
    `${TERRAFORM_SMS_CONFIGURATION_PATTERN} => \`# SMS MFA configuration. Due to a Terraform AWS provider limitation, this also gates
  # SMS-based phone number verification below - see the mfa_second_factor_sms variable.
  dynamic "sms_configuration" {
    for_each = var.mfa_second_factor_sms ? [1] : []

    content {
      external_id    = random_uuid.sms_external_id[0].result
      sns_caller_arn = aws_iam_role.cognito_sms_role[0].arn
      sns_region     = data.aws_region.current.region
    }
  }\``,
  ],
  [
    TERRAFORM_SMS_ROLE_ID_REF_PATTERN,
    `${TERRAFORM_SMS_ROLE_ID_REF_PATTERN} => \`aws_iam_role.cognito_sms_role[0].id\``,
  ],
  [
    TERRAFORM_EXTERNAL_ID_REF_PATTERN,
    `${TERRAFORM_EXTERNAL_ID_REF_PATTERN} => \`random_uuid.sms_external_id[0].result\``,
  ],
  [
    TERRAFORM_AUTO_VERIFIED_ATTRIBUTES_PATTERN,
    `${TERRAFORM_AUTO_VERIFIED_ATTRIBUTES_PATTERN} => \`auto_verified_attributes = var.mfa_second_factor_sms ? ["email", "phone_number"] : ["email"]\``,
  ],
  [
    TERRAFORM_ATTRIBUTES_REQUIRE_VERIFICATION_PATTERN,
    `${TERRAFORM_ATTRIBUTES_REQUIRE_VERIFICATION_PATTERN} => \`attributes_require_verification_before_update = var.mfa_second_factor_sms ? ["email", "phone_number"] : ["email"]\``,
  ],
];

const TERRAFORM_MAIN_ENABLE_WAF_VARIABLE_ANCHOR = [
  'language hcl',
  '`variable "enable_waf" {',
  '  description = "Whether to enable AWS WAFv2 with the default managed ruleset and associate it with the user pool"',
  '  type        = bool',
  '  default     = true',
  '}`',
].join('\n');

const TERRAFORM_MAIN_MODULE_PATTERN = [
  'language hcl',
  '`module "identity" {',
  '  source = "./identity"',
  '',
  '  user_pool_domain_prefix = $prefix',
  '  allow_signup = $allowSignup',
  '  enable_waf = var.enable_waf',
  '}`',
].join('\n');

const TERRAFORM_MAIN_EDITS: Array<[string, string]> = [
  [
    TERRAFORM_MAIN_ENABLE_WAF_VARIABLE_ANCHOR,
    `${TERRAFORM_MAIN_ENABLE_WAF_VARIABLE_ANCHOR} => \`variable "enable_waf" {
  description = "Whether to enable AWS WAFv2 with the default managed ruleset and associate it with the user pool"
  type        = bool
  default     = true
}

${NEW_TERRAFORM_VARIABLES}\``,
  ],
  [
    TERRAFORM_MAIN_MODULE_PATTERN,
    `${TERRAFORM_MAIN_MODULE_PATTERN} => \`module "identity" {
  source = "./identity"

  user_pool_domain_prefix = $prefix
  allow_signup = $allowSignup
  enable_waf = var.enable_waf
  mfa = var.mfa
  mfa_second_factor_otp = var.mfa_second_factor_otp
  mfa_second_factor_sms = var.mfa_second_factor_sms
}\``,
  ],
];

const divergedNextStep = (filePath: string) =>
  `${filePath}: the UserIdentity construct/module has diverged from the generated shape - left untouched. To make MFA configurable, add mfa and mfaSecondFactor (CDK) / mfa, mfa_second_factor_otp and mfa_second_factor_sms (Terraform) yourself, following the same pattern as the existing enableWaf prop/variable.`;

const applyEdits = async (
  tree: Tree,
  filePath: string,
  migratedPattern: string,
  edits: Array<[string, string]>,
  nextSteps: string[],
  beforeApply?: () => Promise<void>,
) => {
  if (!tree.exists(filePath)) {
    // This workspace doesn't use this IaC provider, or has no UserIdentity.
    return;
  }

  if (await matchGritQL(tree, filePath, migratedPattern)) {
    // Already migrated - silent skip keeps re-runs a no-op.
    return;
  }

  // Confirm every edit site is present before writing any of them, so a file
  // that only partly matches is left whole rather than half-edited.
  const allSitesPresent = (
    await Promise.all(
      edits.map(([match]) => matchGritQL(tree, filePath, match)),
    )
  ).every(Boolean);

  if (!allSitesPresent) {
    nextSteps.push(divergedNextStep(filePath));
    return;
  }

  await beforeApply?.();

  for (const [, rewrite] of edits) {
    await applyGritQL(tree, filePath, rewrite);
  }
};

export default async function migration(
  tree: Tree,
): Promise<MigrationReturnObject> {
  const nextSteps: string[] = [];

  await applyEdits(
    tree,
    CDK_USER_IDENTITY_FILE,
    CDK_MIGRATED_PATTERN,
    CDK_EDITS,
    nextSteps,
    () =>
      addDestructuredImport(
        tree,
        CDK_USER_IDENTITY_FILE,
        ['type MfaSecondFactor'],
        'aws-cdk-lib/aws-cognito',
      ),
  );

  await applyEdits(
    tree,
    TERRAFORM_IDENTITY_FILE,
    TERRAFORM_IDENTITY_MIGRATED_PATTERN,
    TERRAFORM_IDENTITY_EDITS,
    nextSteps,
  );

  await applyEdits(
    tree,
    TERRAFORM_MAIN_FILE,
    TERRAFORM_MAIN_MIGRATED_PATTERN,
    TERRAFORM_MAIN_EDITS,
    nextSteps,
  );

  await formatFilesInSubtree(tree);

  return { nextSteps };
}
