/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import {
  getProjects,
  type MigrationReturnObject,
  type TargetConfiguration,
  type Tree,
  updateProjectConfiguration,
} from '@nx/devkit';
import { INFRA_APP_GENERATOR_INFO } from '../../../infra/app/generator.js';
import { formatFilesInSubtree } from '../../../utils/format.js';

/**
 * Deploy using CloudFormation express mode from the deploy and deploy-sandbox
 * targets of ts#infra projects
 *
 * Express mode completes each resource operation as soon as its configuration
 * is applied rather than waiting for full stabilization, which is a much faster
 * iteration cycle for development deploys.
 *
 * Two targets keep waiting for full stabilization: `deploy-ci`, since pipeline
 * deployments should never skip it, and - when stages are configured - `deploy`,
 * which deploys whichever stage is named, including beta and prod.
 */

const DEPLOY_TARGETS = ['deploy', 'deploy-sandbox'];

const EXPRESS_FLAG = '--express';

/**
 * Whether the command is one of the deploy commands this migration vends -
 * either a direct `cdk deploy`, or the stage-config `infra-deploy.ts` script
 * that wraps it. Anything else has been hand-written and is reported rather
 * than rewritten.
 */
const isGeneratedDeployCommand = (command: string): boolean =>
  /(^|\s)cdk\s+deploy(\s|$)/.test(command) ||
  command.includes('infra-deploy.ts');

/** Whether the command runs the stage-config deploy script. */
const isStageConfigDeploy = (command: string): boolean =>
  command.includes('infra-deploy.ts');

const divergedNextStep = (projectName: string, target: string): string =>
  `${projectName}: its ${target} target has been customised, so it was left as it is. Add "${EXPRESS_FLAG}" to the target's command to deploy using CloudFormation express mode.`;

export default async function migration(
  tree: Tree,
): Promise<MigrationReturnObject> {
  const nextSteps: string[] = [];
  let migrated = false;

  for (const [name, project] of getProjects(tree)) {
    if (
      (project.metadata as { generator?: string } | undefined)?.generator !==
      INFRA_APP_GENERATOR_INFO.id
    ) {
      continue;
    }

    let projectChanged = false;

    for (const targetName of DEPLOY_TARGETS) {
      const target: TargetConfiguration | undefined =
        project.targets?.[targetName];
      const command = target?.options?.command;
      if (!target || typeof command !== 'string') {
        continue;
      }

      // Already migrated (or generated by a version that already passes it) -
      // skip so re-running is a no-op.
      if (command.split(/\s+/).includes(EXPRESS_FLAG)) {
        continue;
      }

      // `--no-express` is a deliberate opt-out, so honour it rather than
      // flipping the user back to express mode.
      if (command.split(/\s+/).includes('--no-express')) {
        continue;
      }

      if (!isGeneratedDeployCommand(command)) {
        nextSteps.push(divergedNextStep(name, targetName));
        continue;
      }

      // When stages are configured, `deploy` deploys whichever stage is named,
      // including beta and prod, so it stays on full stabilization. Only its
      // sandbox counterpart opts into express mode.
      if (targetName === 'deploy' && isStageConfigDeploy(command)) {
        continue;
      }

      // Appended last so it stays clear of the stage pattern, which the
      // stage-config deploy script reads from the first positional argument.
      target.options.command = `${command} ${EXPRESS_FLAG}`;
      projectChanged = true;
    }

    if (projectChanged) {
      updateProjectConfiguration(tree, name, project);
      migrated = true;
    }
  }

  if (migrated) {
    await formatFilesInSubtree(tree);
  }

  return { nextSteps };
}
