name: Initialize Monorepo
description: Initialize nx monorepo for CI workflows

runs:
  using: 'composite'
  steps:
    - name: Use PNPM 9.x
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: oven-sh/setup-bun@v2
      with:
        # Nx does not currently support the text-based lockfile which is the default in bun 1.2
        # https://github.com/nrwl/nx/issues/30362
        # https://github.com/nrwl/nx/issues/30607
        # We can change this back to 'latest' once these issues are resolved.
        bun-version: 1.1.45
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        version: 'latest'
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install Node.js Dependencies
      shell: bash
      run: pnpm i --frozen-lockfile --prefer-offline
    - name: Set git identity
      shell: bash
      run: |-
        git config user.name "release"
        git config user.email "release@github.com"
    - uses: nrwl/nx-set-shas@v4
