name: Initialize Monorepo
description: Initialize nx monorepo for CI workflows

inputs:
  aws-docker-login-role-arn:
    description: 'ARN of the AWS role to assume for Docker login'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Docker login credentials
      if: ${{ inputs.aws-docker-login-role-arn != '' }}
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ inputs.aws-docker-login-role-arn }}
        aws-region: us-east-1
    - name: Login to ECR
      if: ${{ inputs.aws-docker-login-role-arn != '' }}
      uses: docker/login-action@v3
      with:
        registry: public.ecr.aws
    - name: Use PNPM 10.x
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.6
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5
      with:
        version: 'latest'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        image: public.ecr.aws/eks-distro-build-tooling/binfmt-misc:qemu-v7.0.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Set up terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.13.1'
    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Update NPM
      shell: bash
      run: npm i -g npm@11.6.1
    - name: Install Node.js Dependencies
      shell: bash
      run: pnpm i --frozen-lockfile --prefer-offline
    - name: Set git identity
      shell: bash
      run: |-
        git config user.name "release"
        git config user.email "release@github.com"
    - uses: nrwl/nx-set-shas@v4
