/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import {
  type GeneratorCallback,
  joinPathFragments,
  type ProjectConfiguration,
  type Tree,
  updateProjectConfiguration,
} from '@nx/devkit';
import { formatFilesInSubtree } from '../../utils/format';
import { FsCommands } from '../../utils/fs';
import { updateGitIgnore } from '../../utils/git';
import { installDependencies } from '../../utils/install';
import { addGeneratorMetricsIfApplicable } from '../../utils/metrics';
import {
  addDependencyToTargetIfNotPresent,
  getGeneratorInfo,
  type NxGeneratorInfo,
  readProjectConfigurationUnqualified,
} from '../../utils/nx';
import { SMITHY_PROJECT_GENERATOR_INFO } from '../project/generator';
import {
  ensureSmithyDepsSupport,
  readSmithyDependencies,
  SMITHY_DEPS_DIR,
  smithyDepDirName,
  smithyDepPath,
} from '../project/smithy-deps';
import { TS_SMITHY_API_GENERATOR_INFO } from '../ts/api/generator';
import type { SmithyModelConnectionGeneratorSchema } from './schema';

export const SMITHY_MODEL_CONNECTION_GENERATOR_INFO: NxGeneratorInfo =
  getGeneratorInfo(import.meta.filename);

export const COPY_MODEL_DEPS_TARGET = 'copy-model-deps';

export const smithyModelConnectionGenerator = async (
  tree: Tree,
  options: SmithyModelConnectionGeneratorSchema,
): Promise<GeneratorCallback> => {
  // The dependency is consumed by the model, which for an API project is a
  // separate project to the one the user names
  const modelProjectConfig = resolveModelProject(tree, options.sourceProject);
  const libraryProjectConfig = readProjectConfigurationUnqualified(
    tree,
    options.targetProject,
  );

  validateShapeLibrary(libraryProjectConfig);

  if (modelProjectConfig.name === libraryProjectConfig.name) {
    throw new Error(
      `Cannot connect Smithy project ${modelProjectConfig.name} to itself.`,
    );
  }

  // A shape library's own dependencies are recorded transitively, so the
  // library's set plus the library itself is the full set to add
  const libraryDependencies = readSmithyDependencies(libraryProjectConfig);

  if (libraryDependencies.includes(modelProjectConfig.name)) {
    throw new Error(
      `Cannot connect Smithy project ${modelProjectConfig.name} to ${libraryProjectConfig.name}, since ${libraryProjectConfig.name} already depends on it. Smithy shape library dependencies cannot be circular.`,
    );
  }

  // Sorted so that the generated commands are stable across re-runs
  const dependencies = [
    ...new Set([
      ...readSmithyDependencies(modelProjectConfig),
      libraryProjectConfig.name,
      ...libraryDependencies,
    ]),
  ].sort();

  // Configure the Dockerfile and smithy-build.json to load the copied shapes.
  // Projects generated by smithy#project since shape library support was added
  // need no changes here, but older ones do.
  ensureSmithyDepsSupport(tree, modelProjectConfig.root);

  const cmd = new FsCommands(tree);

  // Smithy models are resolved by the Smithy CLI inside a Docker build whose
  // context is the project directory, so each dependency's sources are copied
  // in before the model is built.
  modelProjectConfig.targets[COPY_MODEL_DEPS_TARGET] = {
    cache: true,
    // Declared explicitly rather than relying on the workspace's default
    // inputs, so a change to a shape library invalidates the copy
    inputs: [
      {
        dependentTasksOutputFiles: '**/*',
      },
    ],
    executor: 'nx:run-commands',
    options: {
      commands: [
        // Wiped and rebuilt each time so that shapes from a library which is no
        // longer depended on don't linger in the model
        cmd.rm(`{projectRoot}/${SMITHY_DEPS_DIR}`),
        cmd.mkdir(`{projectRoot}/${SMITHY_DEPS_DIR}`),
        ...dependencies.map((dependency) =>
          cmd.cp(
            joinPathFragments(
              readProjectConfigurationUnqualified(tree, dependency).root,
              'src',
            ),
            smithyDepPath('{projectRoot}', smithyDepDirName(dependency)),
          ),
        ),
      ],
      parallel: false,
    },
    outputs: [`{projectRoot}/${SMITHY_DEPS_DIR}`],
    dependsOn: dependencies.map((dependency) => `${dependency}:build`),
  };

  addDependencyToTargetIfNotPresent(
    modelProjectConfig,
    'compile',
    COPY_MODEL_DEPS_TARGET,
  );

  modelProjectConfig.metadata = {
    ...modelProjectConfig.metadata,
    smithyDependencies: dependencies,
  } as unknown;

  updateProjectConfiguration(tree, modelProjectConfig.name, modelProjectConfig);

  // Copied shapes are build artifacts owned by the copy-model-deps target
  updateGitIgnore(tree, modelProjectConfig.root, (patterns) => [
    ...patterns,
    `${SMITHY_DEPS_DIR}/`,
  ]);

  await addGeneratorMetricsIfApplicable(tree, [
    SMITHY_MODEL_CONNECTION_GENERATOR_INFO,
  ]);

  await formatFilesInSubtree(tree);
  return () =>
    installDependencies(tree, options.preferInstallDependencies, {
      languages: ['typescript'],
    });
};

/**
 * Resolve the Smithy model project which consumes the shape library. The user
 * may name either a smithy#project directly, or a ts#smithy-api project, in
 * which case the model project associated with it is used.
 */
const resolveModelProject = (
  tree: Tree,
  projectName: string,
): ProjectConfiguration => {
  const projectConfig = readProjectConfigurationUnqualified(tree, projectName);
  const generator = ((projectConfig.metadata as any) ?? {}).generator;

  if (generator === SMITHY_PROJECT_GENERATOR_INFO.id) {
    return projectConfig;
  }

  if (generator === TS_SMITHY_API_GENERATOR_INFO.id) {
    const modelProjectName = ((projectConfig.metadata as any) ?? {})
      .modelProject;
    if (!modelProjectName) {
      throw new Error(
        `Could not find associated model for Smithy backend project ${projectConfig.name}`,
      );
    }
    return readProjectConfigurationUnqualified(tree, modelProjectName);
  }

  throw new Error(
    `Unsupported connection source ${projectConfig.name}. Expected a Smithy project or a Smithy API.`,
  );
};

/**
 * Check the connection target is a Smithy project whose shapes can be consumed
 */
const validateShapeLibrary = (projectConfig: ProjectConfiguration) => {
  const metadata = (projectConfig.metadata as any) ?? {};

  if (metadata.generator !== SMITHY_PROJECT_GENERATOR_INFO.id) {
    throw new Error(
      `Unsupported connection target ${projectConfig.name}. Expected a Smithy project generated by ${SMITHY_PROJECT_GENERATOR_INFO.id}.`,
    );
  }

  if (metadata.backendProject) {
    throw new Error(
      `Cannot connect to ${projectConfig.name}, since it is the model for the API ${metadata.backendProject}. Generate a shape library with "${SMITHY_PROJECT_GENERATOR_INFO.id} --type=shapes" to share shapes between Smithy projects.`,
    );
  }
};

export default smithyModelConnectionGenerator;
