/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import {
  getProjects,
  joinPathFragments,
  type MigrationReturnObject,
  type ProjectConfiguration,
  readProjectConfiguration,
  type Tree,
  updateProjectConfiguration,
} from '@nx/devkit';
import { REACT_WEBSITE_APP_GENERATOR_INFO } from '../../../ts/react-website/app/generator.js';
import { COGNITO_AUTH_GENERATOR_INFO } from '../../../ts/react-website/cognito-auth/generator.js';
import { applyGritQL, matchGritQL } from '../../../utils/ast.js';
import { formatFilesInSubtree } from '../../../utils/format.js';
import type { Iac } from '../../../utils/iac.js';
import { addLocalCallbackUrl } from '../../../utils/identity-constructs/identity-constructs.js';
import {
  addComponentGeneratorMetadata,
  type ComponentMetadata,
} from '../../../utils/nx.js';
import {
  assignPort,
  getExistingComponentPort,
  getExistingProjectPort,
} from '../../../utils/port.js';

/**
 * Assign each react-website project its own dev-server and preview port, and allow-list them for any connected Cognito auth
 *
 * Before this migration every react-website project's `vite.config.mts` hardcoded
 * `server.port: 4200` / `preview.port: 4300`. Vite itself already auto-increments
 * past a port already in use, so multiple websites don't actually collide when run
 * concurrently — but which port each one lands on then depends on start order and
 * can't be known ahead of time. Today's generator assigns each website an explicit,
 * deterministic port (tracked in project metadata, mirroring `assignPort`'s existing
 * use elsewhere) specifically so it can be allow-listed on the shared Cognito
 * construct/module for any website that has added auth. This migration backfills
 * both for existing workspaces.
 *
 * How to write a migration:
 * - https://nx.dev/docs/kb/migration-generators
 * - What `nextSteps` means: https://nx.dev/docs/reference/devkit/MigrationReturnObject
 *
 * Guardrails:
 * - Transform source with GritQL (`applyGritQL`, `matchGritQL`), not regexes or
 *   string replacements: it matches the AST, so it holds up against however the
 *   user's copy has been formatted. Use `updateJson` for JSON.
 * - Pattern-match before writing: skip files that have diverged from the shape
 *   your generators produce and report them via `nextSteps`, or consider a
 *   hybrid migration, rather than clobbering the user's changes.
 * - `nextSteps` is for work left for the user to do by hand, not a log of the
 *   edits you made: an edit that applied cleanly needs no entry.
 * - Idempotent: re-running must be a no-op.
 * - Format what you write: finish with `formatFilesInSubtree` so the files your
 *   migration wrote are formatted correctly.
 */

interface WebsiteProjectMetadata {
  readonly generator?: string;
  readonly components?: ComponentMetadata[];
}

/**
 * Set a vite.config.mts `server`/`preview` block's port. Checks whether it
 * already holds the target value first — the rewrite pattern is a no-op
 * `port: N` => `port: N` in that case, which GritQL reports as "no match"
 * indistinguishably from the block not existing at all.
 */
const patchVitePort = async (
  tree: Tree,
  viteConfigPath: string,
  target: 'server' | 'preview',
  port: number,
): Promise<boolean> => {
  if (!tree.exists(viteConfigPath)) {
    return false;
  }
  const alreadyCorrect = await matchGritQL(
    tree,
    viteConfigPath,
    `\`${target}: { $props }\` where { $props <: contains \`port: ${port}\` }`,
  );
  if (alreadyCorrect) {
    return true;
  }
  return applyGritQL(
    tree,
    viteConfigPath,
    `\`${target}: { $props }\` where { $props <: contains \`port: $_\` => \`port: ${port}\` }`,
  );
};

const PREVIEW_COMPONENT = {
  info: REACT_WEBSITE_APP_GENERATOR_INFO,
  name: 'preview',
};

export default async function migration(
  tree: Tree,
): Promise<MigrationReturnObject> {
  const nextSteps: string[] = [];

  // Deterministic order so re-runs (and different machines migrating the same
  // workspace) assign the same ports.
  const websiteNames: string[] = [...getProjects(tree).entries()]
    .filter(
      ([, project]) =>
        (project.metadata as WebsiteProjectMetadata | undefined)?.generator ===
        REACT_WEBSITE_APP_GENERATOR_INFO.id,
    )
    .map(([name]) => name)
    .sort((a, b) => a.localeCompare(b));

  for (const name of websiteNames) {
    const project: ProjectConfiguration = readProjectConfiguration(tree, name);
    const needsDevPort = getExistingProjectPort(project) === undefined;
    const needsPreviewPort =
      getExistingComponentPort(project, PREVIEW_COMPONENT) === undefined;

    if (!needsDevPort && !needsPreviewPort) {
      // Already migrated (or generated by a version that already assigns
      // ports) - skip so re-running is a no-op.
      continue;
    }

    const viteConfigPath = joinPathFragments(project.root, 'vite.config.mts');
    let previewPort: number | undefined;

    if (needsDevPort) {
      const port = assignPort(tree, project, 4200);
      if (!(await patchVitePort(tree, viteConfigPath, 'server', port))) {
        nextSteps.push(
          `${viteConfigPath}: could not find the expected 'server' block to set its dev-server port to ${port} - set it by hand so it matches the Cognito callback URL this migration is allow-listing for it.`,
        );
      }
    }

    if (needsPreviewPort) {
      previewPort = assignPort(tree, project, 4300, {
        component: PREVIEW_COMPONENT,
      });
      if (
        !(await patchVitePort(tree, viteConfigPath, 'preview', previewPort))
      ) {
        nextSteps.push(
          `${viteConfigPath}: could not find the expected 'preview' block to set its port to ${previewPort} - set it by hand so it matches the Cognito callback URL this migration is allow-listing for it.`,
        );
      }
    }

    // Persists the port(s) assignPort just recorded on `project.metadata.ports`
    // above, before the 'preview' component entry below is added via its own
    // independent read-modify-write - otherwise that read would miss the
    // mutation still sitting only in this in-memory project object.
    updateProjectConfiguration(tree, name, project);

    if (previewPort !== undefined) {
      addComponentGeneratorMetadata(
        tree,
        name,
        REACT_WEBSITE_APP_GENERATOR_INFO,
        'vite.config.mts',
        'preview',
        { port: previewPort },
      );
    }
  }

  // Allow-list the (possibly just-assigned) ports of every website that has
  // added Cognito auth, on whichever shared identity construct/module it uses.
  // Re-reads each project fresh: the pass above may have added its 'preview'
  // component entry via its own read-modify-write, which an in-memory object
  // held over from that pass wouldn't reflect.
  for (const name of websiteNames) {
    const project = readProjectConfiguration(tree, name);
    const authComponent = (
      (project.metadata as WebsiteProjectMetadata | undefined)?.components ?? []
    ).find((c) => c.generator === COGNITO_AUTH_GENERATOR_INFO.id);
    if (!authComponent) {
      continue;
    }

    const devPort = getExistingProjectPort(project);
    const previewPort = getExistingComponentPort(project, PREVIEW_COMPONENT);
    const iac = authComponent.iac as Iac | undefined;
    if (devPort === undefined || previewPort === undefined || !iac) {
      // Shouldn't happen: the pass above assigns both to every website project.
      continue;
    }

    for (const port of [devPort, previewPort]) {
      if (!(await addLocalCallbackUrl(tree, iac, port))) {
        nextSteps.push(
          `The shared Cognito user identity ${iac === 'cdk' ? 'construct' : 'module'} has diverged from the generated shape - left untouched. To sign in against ${name}'s local dev server on port ${port}, add 'http://localhost:${port}' to its local callback/logout URLs by hand.`,
        );
      }
    }
  }

  await formatFilesInSubtree(tree);

  return { nextSteps };
}
