/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import { getProjects, Tree, updateProjectConfiguration } from '@nx/devkit';

/**
 * Migrates projects generated by ts#react-website to include the framework
 * metadata field, enabling the new ts#website generator to detect
 * existing projects.
 */
export default function migrateWebsiteRename(tree: Tree) {
  const projects = getProjects(tree);

  for (const [name, config] of projects) {
    const metadata = config.metadata as any;
    if (!metadata) continue;

    if (metadata.generator === 'ts#react-website' && !metadata.framework) {
      updateProjectConfiguration(tree, name, {
        ...config,
        metadata: {
          ...metadata,
          framework: 'React',
        },
      });
    }

    if (metadata.components && Array.isArray(metadata.components)) {
      let updated = false;
      const components = metadata.components.map((component: any) => {
        if (
          component.generator === 'ts#react-website#auth' ||
          component.generator === 'ts#react-website#runtime-config'
        ) {
          updated = true;
          return component;
        }
        return component;
      });
      if (updated) {
        updateProjectConfiguration(tree, name, {
          ...config,
          metadata: {
            ...metadata,
            components,
          },
        });
      }
    }
  }
}
