/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import { generateFiles, Tree } from '@nx/devkit';
import * as path from 'path';
import { OpenApiPyClientGeneratorSchema } from './schema';
import { buildOpenApiCodeGenerationData } from '../ts-client/generator';
import { CodeGenData } from '../utils/codegen-data/types';
import { formatFilesInSubtree } from '../../utils/format';
import { NxGeneratorInfo, getGeneratorInfo } from '../../utils/nx';
import { addGeneratorMetricsIfApplicable } from '../../utils/metrics';
import { IPyDepVersion, withPyVersions } from '../../utils/versions';

export const OPEN_API_PY_CLIENT_GENERATOR_INFO: NxGeneratorInfo =
  getGeneratorInfo(__filename);

/**
 * Python dependencies required by any project that consumes a client
 * generated by `open-api#py-client`.  Connection generators that wire this
 * generator into a consumer project should add these at the pinned versions
 * from `versions.ts`.
 */
export const OPEN_API_PY_CLIENT_PYTHON_DEPS: readonly IPyDepVersion[] = [
  'httpx',
  'pydantic',
] as const;

/** Fully-qualified version specifiers, e.g. `['httpx==0.28.1', 'pydantic==2.13.2']`. */
export const OPEN_API_PY_CLIENT_PYTHON_DEP_SPECS: string[] = withPyVersions([
  ...OPEN_API_PY_CLIENT_PYTHON_DEPS,
]);

/**
 * Generate a Python httpx-based client from an OpenAPI spec.
 *
 * Emits:
 *  - types_gen.py        — pydantic v2 models + per-op error classes and TypedDicts
 *  - client_gen.py       — sync  client (httpx.Client)       when clientType includes 'sync'
 *  - async_client_gen.py — async client (httpx.AsyncClient) when clientType includes 'async'
 */
export const openApiPyClientGenerator = async (
  tree: Tree,
  options: OpenApiPyClientGeneratorSchema,
) => {
  const data = await buildOpenApiCodeGenerationData(
    tree,
    options.openApiSpecPath,
  );
  const clientType = options.clientType ?? 'both';

  generatePyClient(tree, data, options.outputPath, clientType);

  await addGeneratorMetricsIfApplicable(tree, [
    OPEN_API_PY_CLIENT_GENERATOR_INFO,
  ]);

  await formatFilesInSubtree(tree);
};

/**
 * Generate Python client files from prepared codegen data.
 */
export const generatePyClient = (
  tree: Tree,
  data: CodeGenData,
  outputPath: string,
  clientType: 'sync' | 'async' | 'both',
) => {
  const base = { ...data, clientType, tmpl: '' };

  generateFiles(
    tree,
    path.join(__dirname, 'files', 'shared'),
    outputPath,
    base,
  );

  if (clientType === 'sync' || clientType === 'both') {
    generateFiles(
      tree,
      path.join(__dirname, 'files', 'sync'),
      outputPath,
      base,
    );
  }
  if (clientType === 'async' || clientType === 'both') {
    generateFiles(
      tree,
      path.join(__dirname, 'files', 'async'),
      outputPath,
      base,
    );
  }
};

export default openApiPyClientGenerator;
