/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import { existsSync, rmSync } from 'node:fs';
import { ensureDirSync } from 'fs-extra';
import { afterAll, afterEach, beforeEach, describe, it } from 'vitest';
import { pinAwsScopeToLocalRegistry, tmpProjPath } from '../utils';
import { MIGRATE_NPMRC_EXTRA, runMigrateTest } from './migrate';
import { migrateShard, migrateStartVersions } from './migrate-versions';

/**
 * migrate smoke test — upgrades a workspace generated by a released version of
 * the plugin to the local build with `nx migrate`, and asserts the migrated
 * workspace is still green.
 *
 * This is the regression net for migrations: unit tests prove a migration does
 * what it was written to do against a synthetic tree, but only a real upgrade
 * of a real workspace catches ordering problems, interactions between
 * migrations, and drift between what a migration writes and what today's
 * generators produce.
 *
 * One `it` per start version so a failure names the hop that broke. Each hop
 * scaffolds, migrates and builds a whole workspace, so hops are spread across
 * machines with `NX_E2E_SHARD=<index>/<total>` rather than run back to back
 * (see `migrateStartVersions`).
 *
 * A hop whose start version predates `internal#test-matrix` skips itself, so
 * until a release ships that generator every hop skips and this lane proves
 * nothing. The summary at the end says so explicitly rather than leaving a green
 * tick to imply coverage that isn't there.
 */
const shard = migrateShard();
const startVersions = migrateStartVersions();
const shardLabel = `shard ${shard.index}/${shard.total}`;

if (startVersions.length === 0) {
  console.warn(
    `migrate smoke test: ${shardLabel} has no start versions to migrate from — fewer releases in the supported range than shards, so this shard asserted nothing.`,
  );
}

describe.skipIf(startVersions.length === 0)('smoke test - migrate', () => {
  const outcomes: { startVersion: string; migrated: boolean }[] = [];

  afterAll(() => {
    const migrated = outcomes.filter((o) => o.migrated);
    if (migrated.length === 0) {
      console.warn(
        `migrate smoke test (${shardLabel}): no hop actually migrated (${outcomes.length} skipped) — no release in the supported range vends the generator the hops scaffold with, so this shard asserted nothing.`,
      );
    } else {
      console.log(
        `migrate smoke test (${shardLabel}): migrated from ${migrated.map((o) => o.startVersion).join(', ')} (${outcomes.length - migrated.length} skipped).`,
      );
    }
  });

  for (const startVersion of startVersions) {
    const variant = `from-${startVersion}`;
    const targetDir = `${tmpProjPath()}/migrate-${variant}`;

    describe(variant, () => {
      beforeEach(() => {
        console.log(`Cleaning target directory ${targetDir}`);
        if (existsSync(targetDir)) {
          rmSync(targetDir, { force: true, recursive: true });
        }
        ensureDirSync(targetDir);
        pinAwsScopeToLocalRegistry(targetDir, MIGRATE_NPMRC_EXTRA);
      });

      afterEach(() => {
        if (existsSync(targetDir)) {
          rmSync(targetDir, { force: true, recursive: true });
        }
      });

      it(`should migrate a workspace from ${startVersion} and still build`, async () => {
        const result = await runMigrateTest(targetDir, startVersion);
        outcomes.push({ startVersion, migrated: !!result });
      });
    });
  }
});
