/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import { existsSync, rmSync } from 'node:fs';
import { ensureDirSync } from 'fs-extra';
import { afterEach, beforeEach, describe, it } from 'vitest';
import { pinAwsScopeToLocalRegistry, tmpProjPath } from '../utils';
import { MIGRATE_NPMRC_EXTRA, runMigrateTest } from './migrate';
import { migrateStartVersions } from './migrate-versions';

/**
 * migrate smoke test — upgrades a workspace generated by a released version of
 * the plugin to the local build with `nx migrate`, and asserts the migrated
 * workspace is still green.
 *
 * This is the regression net for migrations: unit tests prove a migration does
 * what it was written to do against a synthetic tree, but only a real upgrade
 * of a real workspace catches ordering problems, interactions between
 * migrations, and drift between what a migration writes and what today's
 * generators produce.
 *
 * One `it` per start version so a failure names the hop that broke.
 */
describe('smoke test - migrate', () => {
  const startVersions = migrateStartVersions();

  for (const startVersion of startVersions) {
    const variant = `from-${startVersion}`;
    const targetDir = `${tmpProjPath()}/migrate-${variant}`;

    describe(variant, () => {
      beforeEach(() => {
        console.log(`Cleaning target directory ${targetDir}`);
        if (existsSync(targetDir)) {
          rmSync(targetDir, { force: true, recursive: true });
        }
        ensureDirSync(targetDir);
        pinAwsScopeToLocalRegistry(targetDir, MIGRATE_NPMRC_EXTRA);
      });

      afterEach(() => {
        if (existsSync(targetDir)) {
          rmSync(targetDir, { force: true, recursive: true });
        }
      });

      it(`should migrate a workspace from ${startVersion} and still build`, async () => {
        await runMigrateTest(targetDir, startVersion);
      });
    });
  }
});
