/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
import {
  type GeneratorCallback,
  installPackagesTask,
  joinPathFragments,
  type Tree,
  updateProjectConfiguration,
} from '@nx/devkit';
import { formatFilesInSubtree } from '../../../utils/format';
import { addGeneratorMetricsIfApplicable } from '../../../utils/metrics';
import { kebabCase } from '../../../utils/names';
import {
  addDependencyToTargetIfNotPresent,
  getGeneratorInfo,
  type NxGeneratorInfo,
  readProjectConfigurationUnqualified,
} from '../../../utils/nx';
import type { AgentcoreGatewayMcpConnectionGeneratorSchema } from './schema';

export const AGENTCORE_GATEWAY_MCP_CONNECTION_GENERATOR_INFO: NxGeneratorInfo =
  getGeneratorInfo(__filename);

/**
 * Connect an AgentCore Gateway to an MCP server.
 *
 * This generator wires up everything that can be automated without editing
 * the user's application stack:
 *
 * 1. Chains the gateway's `serve-local` aggregator target to the MCP
 *    server's `serve-local` target so `nx serve-local` on an agent
 *    transitively starts every attached MCP server.
 * 2. Back-propagates the MCP server binding into any agent-side gateway
 *    client files (`<Gateway>Client.ts` / `_client.py`) generated by the
 *    `*#strands-agent#gateway-connection` generator, so local-mode
 *    multiplexing sees the new server.
 *
 * Users must still call `gateway.addMcpServerTarget(...)` in their
 * application stack to create the actual CDK/Terraform resource. The
 * generator logs instructions on completion.
 */
export const agentcoreGatewayMcpConnectionGenerator = async (
  tree: Tree,
  options: AgentcoreGatewayMcpConnectionGeneratorSchema,
): Promise<GeneratorCallback> => {
  const sourceProject = readProjectConfigurationUnqualified(
    tree,
    options.sourceProject,
  );
  const targetProject = readProjectConfigurationUnqualified(
    tree,
    options.targetProject,
  );

  const gatewayComponent = options.sourceComponent;
  const mcpComponent = options.targetComponent;

  if (!gatewayComponent) {
    throw new Error(
      `Source project '${options.sourceProject}' has no AgentCore Gateway component metadata. Did you run the 'cedar#agentcore-gateway' generator?`,
    );
  }
  if (!mcpComponent) {
    throw new Error(
      `Target project '${options.targetProject}' has no MCP server component metadata. Did you run the 'ts#mcp-server' or 'py#mcp-server' generator?`,
    );
  }

  if (gatewayComponent.protocol !== 'mcp') {
    throw new Error(
      `Gateway '${gatewayComponent.name}' has protocol='${gatewayComponent.protocol}'. MCP server targets can only be attached to MCP-protocol gateways.`,
    );
  }
  if (mcpComponent.auth && mcpComponent.auth !== 'iam') {
    throw new Error(
      `MCP server '${mcpComponent.name}' uses auth='${mcpComponent.auth}'. Gateway->MCP connections currently require the MCP server to use IAM authentication.`,
    );
  }

  const gatewayClassName = gatewayComponent.rc as string;
  const gatewayKebabCase = kebabCase(gatewayClassName);
  const gatewayServeLocalTargetName = `${gatewayKebabCase}-serve-local`;

  const mcpClassName = mcpComponent.rc as string;
  const mcpKebabCase = kebabCase(mcpClassName);
  const mcpComponentName = mcpComponent.name ?? 'mcp-server';
  const mcpServeLocalTargetName = `${mcpComponentName}-serve-local`;
  const mcpPort = (mcpComponent.port as number | undefined) ?? 8000;

  // 1. Wire serve-local chain
  if (sourceProject.targets?.[gatewayServeLocalTargetName]) {
    addDependencyToTargetIfNotPresent(
      sourceProject,
      gatewayServeLocalTargetName,
      {
        projects: [targetProject.name],
        target: mcpServeLocalTargetName,
      },
    );
    updateProjectConfiguration(tree, sourceProject.name, sourceProject);
  }

  // 2. Back-propagate into any existing gateway-connection clients
  await backPropagateMcpServerToGatewayClients(tree, {
    gatewayClassName,
    mcpKebabCase,
    mcpPort,
  });

  await addGeneratorMetricsIfApplicable(tree, [
    AGENTCORE_GATEWAY_MCP_CONNECTION_GENERATOR_INFO,
  ]);

  await formatFilesInSubtree(tree);

  // Print instructions for the user to add the CDK/TF wiring in their stack.
  // This is the one step we can't automate because the generator doesn't
  // know which stack the user will instantiate the gateway in.
  const mcpVarName =
    mcpClassName.charAt(0).toLowerCase() + mcpClassName.slice(1);
  const gatewayVarName =
    gatewayClassName.charAt(0).toLowerCase() + gatewayClassName.slice(1);
  console.log('');
  console.log(
    `✔ Connected ${mcpClassName} MCP server to ${gatewayClassName} gateway.`,
  );
  console.log('');
  console.log('Add the following to the stack that instantiates your gateway:');
  console.log('');
  console.log(
    `  const ${mcpVarName} = new ${mcpClassName}(this, '${mcpClassName}');`,
  );
  console.log(`  ${gatewayVarName}.addMcpServer(${mcpVarName});`);
  console.log('');

  return () => {
    installPackagesTask(tree);
  };
};

/**
 * Scan the workspace for agent projects that have a gateway-connection
 * component targeting the given gateway, and update their generated per-
 * connection client to include the new MCP server in their local multiplex
 * list.
 */
const backPropagateMcpServerToGatewayClients = async (
  tree: Tree,
  params: {
    gatewayClassName: string;
    mcpKebabCase: string;
    mcpPort: number;
  },
): Promise<void> => {
  const gatewayKebab = kebabCase(params.gatewayClassName);

  // TypeScript gateway client (if present)
  const tsClientPath = joinPathFragments(
    'packages',
    'common',
    'agent-connection',
    'src',
    'app',
    `${gatewayKebab}-client.ts`,
  );
  if (tree.exists(tsClientPath)) {
    const content = tree.read(tsClientPath)!.toString();
    if (!content.includes(`'${params.mcpKebabCase}'`)) {
      const entry = `  { name: '${params.mcpKebabCase}', localUrl: 'http://localhost:${params.mcpPort}/mcp' },`;
      const updated = content.replace(
        /(const ATTACHED_MCP_SERVERS: LocalMcpServerBinding\[\] = \[)([\s\S]*?)(\];)/m,
        (_match, open, inner, close) =>
          `${open}${inner.replace(/\s+$/, '')}\n${entry}\n${close}`,
      );
      if (updated !== content) tree.write(tsClientPath, updated);
    }
  }

  // Python gateway client (if present) — locate via recursive search because
  // the module name is workspace-specific.
  const pyClientBasename = `${gatewayKebab.replace(/-/g, '_')}_client.py`;
  const pyClientPath = findFile(
    tree,
    joinPathFragments('packages', 'common', 'agent_connection'),
    pyClientBasename,
  );
  if (pyClientPath) {
    const content = tree.read(pyClientPath)!.toString();
    if (!content.includes(`"${params.mcpKebabCase}"`)) {
      const entry = `    LocalMcpServerBinding(name="${params.mcpKebabCase}", local_url="http://localhost:${params.mcpPort}/mcp"),`;
      const updated = content.replace(
        /(ATTACHED_MCP_SERVERS: list\[LocalMcpServerBinding\] = \[)([\s\S]*?)(\])/m,
        (_match, open, inner, close) =>
          `${open}${inner.replace(/\s+$/, '')}\n${entry}\n${close}`,
      );
      if (updated !== content) tree.write(pyClientPath, updated);
    }
  }
};

const findFile = (
  tree: Tree,
  root: string,
  basename: string,
): string | undefined => {
  if (!tree.exists(root)) return undefined;
  for (const child of tree.children(root)) {
    const full = joinPathFragments(root, child);
    if (!tree.isFile(full)) {
      const recursed = findFile(tree, full, basename);
      if (recursed) return recursed;
    } else if (child === basename) {
      return full;
    }
  }
  return undefined;
};

export default agentcoreGatewayMcpConnectionGenerator;
